Remove unused styles from styles.scss
canonical/ubuntu.com pull request #11329
Opened 2022-03-08 13:39 UTC by petesfrench

## Done

- I went through each style in styles.scss and search the code base for any instance where it was used. If I couldn't find any, I deleted it and any associated reference.

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/
    - Be sure to test on mobile, tablet and desktop screen sizes
- Search the codebase for each style that was removed.

## Issue / Card

Fixes https://github.com/canonical-web-and-design/web-squad/issues/4876

2022-03-08 13:40 UTC, webteam-app commented
Demo starting at https://ubuntu-com-11329.demos.haus

2022-03-08 17:24 UTC, petesfrench commented
Do not merge before the vanilla issues have all been merged

2022-03-08 22:44 UTC, anthonydillon requested changes
Mostly looks good, one comment in the code

2022-03-09 08:51 UTC, petesfrench commented on static/sass/_pattern_lists.scss
> -      padding-left: $sp-medium;
Yes, good catch!

2022-03-11 00:45 UTC, anthonydillon approved these changes
Yep, all looks good to me :+1:

2022-03-17 16:34 UTC, merged