Open-source package licences page
canonical/ubuntu.com pull request #11604
Opened 2022-05-12 22:58 UTC by anthonydillon

## Done
Added an open-source package licences page which loads the data for each release from a static JSON file hosted on assets.

## QA
- Open the demo
- VIsit /legal/open-source-licences
- Check that the first navigation item is selected and the table is populated
- Select other releases and check the navigation works and the table works when the json is correct.
- Impish and Focal desktop have broken source data at the moment

2022-05-18 10:54 UTC, anthonydillon commented
### UX review
**Desktop**

- Releases are by development codename only, should we include the full name (Ubuntu 22.04 LTS Jammy Jellyfish)?
- Very long list - could we use pagination?
- Some basic search or filter would be good - I can take a look if you think it's worth it?
- If we don't implement filters, we should avoid pagination or make sure to include a “show all” in the Show “x” items drop down. If everything is on the screen the user can Ctrl+F. It’s a technical audience so they’ll likely do that. That could be good enough for MVP.

**Mobile**

- The “Toggle side navigation” puts an overlay over the screen, but doesn't offer any options, and I can't get out of it (I'm guessing that's a bug)
- 
- The cells are cut off - might need to use the .p-table--mobile-card class to make it work? I don't know how many people would look at this on a mobile screen, I'm guessing low, so might be OK for MVP? We should do it if it's not difficult.

2022-07-13 08:42 UTC, anthonydillon commented
@ThinGuy have you had a chance to work on the JSON files? This branch is still waiting for them.

2022-08-03 10:29 UTC, anthonydillon commented
@ThinGuy when the new JSON files are ready can you comment here and ping @sowasred2012 so someone on the team and complete and release this project.

Known remaining tasks for the developer that picks this up:
1. Upload the new JSON files to the asset server
2. Update the `data-file` attribute on the navigation items (https://github.com/canonical/ubuntu.com/pull/11604/files#diff-c075bcff4a522ca01a2967e259ef5e8dfa38566aae0f9bb69a87d8db618d75e2R33)
3. Check the navigation items now that all work and the links to the licences work as expected

2022-08-26 08:41 UTC, carkod commented
@ThinGuy are the JSON files ready?

2022-09-08 15:45 UTC, anthonydillon commented
Meet Craig and he said he would have the updated files over to me by tomorrow.

2022-09-13 09:25 UTC, anthonydillon commented
@sowasred2012 nope, chasing again.

2022-09-30 12:17 UTC, anthonydillon commented
Katherine +1'ed via email

2022-09-30 12:28 UTC, steverydz approved these changes
LGTM 👍

2022-09-30 12:31 UTC, steverydz commented on templates/legal/open-source-licences.html
> +        <td data-heading="Licenses"><a href="${package.copyright_url}">${package.licenses}</a></td>
This outputs an empty link which was flagged by the WAVE Chrome extension

2022-09-30 12:31 UTC, steverydz requested changes
One comment in the code

2022-09-30 14:58 UTC, anthonydillon commented
Good catch @steverydz. Fixed.

2022-09-30 16:30 UTC, merged