Fixed mobile footer links and added some padding.
canonical/ubuntu.com pull request #11832
Opened 2022-07-13 12:13 UTC by publikphigor

## Done

- [Increased the font-size of the drop-downs.]
- [Added padding-inline to the drop-downs.]

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/
    - Be sure to test on mobile, tablet and desktop screen sizes
- [The drop-down itself doesn't work yet.]

## Issue / Card
#11831 

Fixes #

## Screenshots

[If relevant, please include a screenshot.]

## Help

[QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html) - [Commit guidelines](https://canonical-web-and-design.github.io/practices/workflow/commit-messages.html)

2022-07-13 12:13 UTC, webteam-app commented
publikphigor is not a collaborator of the repo

2022-07-13 13:17 UTC, anthonydillon requested changes
Thank you for contributing @publikphigor. Were you able to look into the click accordion issue? One small comment in the code.

2022-07-13 13:17 UTC, anthonydillon commented on static/sass/_pattern_footer.scss
> +    padding-inline: 1rem;
I would suggest you simply change the original padding styling on line 103 to `padding: $sp-medium`

2022-07-13 13:58 UTC, publikphigor commented
I found the accordion.js and all look good. I also checked the console and it doesn't throw any error when I click the links.
I suspect they're not selected to run the functions in accordion.js.

2022-07-13 14:28 UTC, anthonydillon commented
Great, thanks @publikphigor. I have created a new issue to [tackle the dropdown action](https://github.com/canonical-web-and-design/ubuntu.com/issues/11834). Just waiting on a design review now.

2022-07-15 09:10 UTC, lyubomir-popov commented
@anthonydillon how do I QA this? There's no demo link.

2022-07-15 10:08 UTC, sowasred2012 commented
@lyubomir-popov here's a demo: https://ubuntu-com-11832.demos.haus/

2022-07-18 19:15 UTC, anthonydillon commented
No this should be fixed in this branch. Would you be ok to look at this @publikphigor

2022-07-18 19:18 UTC, publikphigor commented
I'll look into it @anthonydillon

2022-07-22 16:20 UTC, sowasred2012 commented
@publikphigor hope you don't mind, I made a couple of updates to allow the accordions to open on click - I don't think this is ready yet, I was hoping to get more design guidance from @davegoddard42:

- there are two different font weights going on, 100 (for accordion CTAs) vs 300 for every other link
- I'm not sure we've discussed the design of the links contained in the accordions, at the moment they're just a darker color than standard links (`#111` vs `#666`)

![Peek 2022-07-22 17-16](https://user-images.githubusercontent.com/2376968/180481248-bbd552d7-7a59-49cf-ab21-d385b1b9dde4.gif)

2022-07-22 16:48 UTC, lyubomir-popov commented
> there are two different font weights going on, 100 (for accordion CTAs) vs 300 for every other link

that’s because the css is overriding the font size of h2s, but not the font weight. Ideally we should have a “p-paragraph that does the opposite of”p-heading—-“, to avoid partial overrides that kead to regressions like this.

2022-08-01 08:28 UTC, sowasred2012 commented
@lyubomir-popov would you mind giving this another design review?

2022-08-02 12:28 UTC, davegoddard42 commented
LGTM @sowasred2012 - nice work.

2022-08-02 13:45 UTC, davegoddard42 approved these changes
Outstanding design items addressed - looks good

2022-08-02 13:56 UTC, merged