Remove redundant subnav on cve pages
canonical/ubuntu.com pull request #11983
Opened 2022-08-31 11:43 UTC by mtruj013

## Done

- Removed redundant subnav on CVE pages (see issue for context)

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/security/cves
    - Be sure to test on mobile, tablet and desktop screen sizes
- Visit any CVE page and see that only 1 subnav exists

## Issue / Card

Fixes https://github.com/canonical/ubuntu.com/issues/11982

2022-08-31 11:43 UTC, webteam-app commented
Demo starting at https://ubuntu-com-11983.demos.haus

2022-08-31 14:19 UTC, carkod commented
Can you also fix it for tutorials? https://ubuntu-com-11983.demos.haus/tutorials/manage-ua-client-fips-configurations-at-scale-with-landscape#1-overview

2022-09-01 09:01 UTC, carkod approved these changes
LGTM

2022-09-01 09:02 UTC, carkod requested changes
Oh wait, I don't think it's fixed. Now the individual sections are not showing?

2022-09-01 10:37 UTC, mtruj013 commented
@carkod I was going by what was on the [spreadsheet](https://docs.google.com/spreadsheets/d/1YeTZP9sr2WUX2-N7clirZtGuARD0PMirHk0Ty-WUKU0/edit#gid=987317135) that Dave left. But it does sound weird that they would all link to "How to write a tutorial" now that you mention it. 

@sowasred2012 is the correct subnav link for any given tutorial supposed to be the first section of said tutorial or are they all supposed to link to the same thing?

2022-09-02 11:40 UTC, carkod approved these changes
LGTM. 
Just from a UX perspective:
- The title thingy is quite weird, it's like the line is broken. 
- And shouldn't we use the name of the tutorial as the navigation instead of the "How to write a tutorial?" which is probably irrelevant for most users?

2022-09-02 12:40 UTC, sowasred2012 commented
@carkod in the conversations I had with Dave about the subnav, the idea was for it to be consistent within a particular bubble i.e. the items shouldn't change, and also that we should never use breadcrumbs. Additionally, titles of tutorials can be quite long, and the work we recently did on the subnav was meant to reduce the length and number of items in the subnav ready for when we roll out the new nav design. I agree that "How to write a tutorial" looks odd there though.

2022-09-02 12:46 UTC, merged