Build page on /automotive/developers
canonical/ubuntu.com pull request #12022
Opened 2022-09-12 10:35 UTC by minkyngkm

## Done

- Build page on /automotive/developers

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/
    - Be sure to test on mobile, tablet and desktop screen sizes
- Compare page against [copy doc](https://docs.google.com/document/d/1tO6WLB0Mk4jx_s22Yi2502nfGzsXbuNZCzSr56MnHWw/edit#) 

## Issue / Card

Fixes [#5934](https://github.com/canonical/web-squad/issues/5934)

2022-09-12 10:35 UTC, webteam-app commented
Demo starting at https://ubuntu-com-12022.demos.haus

2022-09-20 13:58 UTC, mtruj013 requested changes
Thanks @minkyngkm, looks great! A couple notes, we made some updates to some of the links in the doc which weren't descriptive enough for users with screen readers. There's also supposed to be a CTA at the top of the page according to the doc.

2022-09-20 13:58 UTC, mtruj013 commented on templates/automotive/developers.html
> +      <p><a href="/support">Simplify compliance. Streamline certification. Protect innovation.</a></p>
```suggestion
      <p><a href="/support">Learn more about support services&nbsp;&rsaquo;</a></p>
```

2022-09-21 07:49 UTC, minkyngkm commented
Thanks @mtruj013 - Nice suggestions!! I've made some changes :)

2022-09-21 10:17 UTC, mtruj013 approved these changes
LGTM!

2022-09-22 08:01 UTC, merged