Refresh /hpc and add contact modal
canonical/ubuntu.com pull request #12231
Opened 2022-10-26 12:58 UTC by petesfrench

## Done

- Refresh /hpc and add contact modal
- Based on [copydoc](https://docs.google.com/document/d/1d4E1IA2mEu72q277sihNSkl7QRKsU1ezwA3jVgJ0TCE/edit#) and [design](https://www.figma.com/proto/NgiuI3rQmyLBljKHyJrZXK/HPC?page-id=7%3A3918&node-id=7%3A3919&viewport=639%2C754%2C0.33&scaling=min-zoom)

## QA

- Compare against copydoc and design

## Issue / Card

Fixes https://github.com/canonical/ubuntu.com/issues/12111

2022-10-26 12:58 UTC, webteam-app commented
Demo starting at https://ubuntu-com-12231.demos.haus

2022-10-26 13:02 UTC, petesfrench commented
@elioqoshi A couple things I wasn't sure about:
1. The design finishes at the webinar/case study section, so can the rest be left how it is? There are two sections that clash quite heavily.
![image](https://user-images.githubusercontent.com/58276363/198032217-eab15d78-352f-4c4a-9690-d313f4832a55.png)
2. In the copydoc the section for 'Ceph' is along with the different Canonical products, but I suppose should be with the other partners?

2022-10-26 13:18 UTC, elioqoshi commented
The latest designs are here and they should have the right latest content: 
https://www.figma.com/file/NgiuI3rQmyLBljKHyJrZXK/HPC?node-id=7%3A3918

2022-10-26 14:17 UTC, petesfrench commented
@elioqoshi I have updated the page according to the design, can you take a look please?

2022-11-01 15:38 UTC, mtruj013 requested changes
Looks good @petesfrench! Just a few things:

2022-11-07 08:38 UTC, petesfrench commented on templates/hpc/index.html
> -  <section class="p-strip">
Good catch! It has moved to the section above

2022-11-07 12:24 UTC, elioqoshi commented
This is looking good to me! Maybe except the logo alignments, which seems different from what @lyubomir-popov suggests?

2022-11-07 14:00 UTC, lyubomir-popov commented
I agree, the logos are far too large.

2022-11-07 15:10 UTC, petesfrench commented
@elioqoshi @lyubomir-popov What do you suggest I do here? This uses the standard vanilla pattern and logos from the updated logo collection Lyubo put together.

2022-11-07 15:58 UTC, petesfrench commented
@lyubomir-popov Ok I understand, I thought were were talking about the logo-section at the top of the page. Updated.

2022-11-08 08:51 UTC, mtruj013 approved these changes
Thanks @petesfrench, looks great! Left a few more comments, but all for super small stuff.

2022-11-08 08:51 UTC, mtruj013 commented on templates/hpc/index.html
>            From energy to healthcare, we help industry leaders ease operations and break new ground with the power of compute.
"Accelerate discovery in:" is bold text on the design

2022-11-08 08:51 UTC, mtruj013 commented on templates/hpc/index.html
>            Deploy HPC and supercomputing clusters with ease.
Gloria [requested](https://docs.google.com/document/d/1d4E1IA2mEu72q277sihNSkl7QRKsU1ezwA3jVgJ0TCE/edit?disco=AAAAeQXgTmk) this be made a single paragraph

2022-11-08 08:52 UTC, mtruj013 commented
Oh also, forgot to mention, the Mercedes logo is different from the one the Pdm requested, not sure if it matters or not though!

2022-11-08 09:30 UTC, petesfrench commented on templates/hpc/index.html
> +        <a class="p-button--positive" href="/hpc/use-cases">See use cases</a>
We should try and give links and buttons directive text. I spoke with @al-bakalova and she has updated doc accordingly

2022-11-10 09:40 UTC, petesfrench commented
@lyubomir-popov Could you take another look at this please

2022-11-11 09:41 UTC, sowasred2012 commented
@lyubomir-popov could either of you give a design review on this please?

2022-11-15 09:45 UTC, elioqoshi commented
This looks good to me now, thank you!

2022-11-15 10:04 UTC, merged