Fix list of tutorial topics/categories
canonical/ubuntu.com pull request #12235
Opened 2022-10-27 10:26 UTC by carkod

## Done

The code duplication (in the template and views function) caused the `Ubuntu advantage` topic to duplicate
Refactored into one single place. Loops should be performant as `continue` should skip the queue if matched.

## QA

- Go to /tutorials
- Check that `Ubuntu advantage` topic is not duplicated and that it does display tutorials

## Issue / Card

Fixes https://github.com/canonical/web-squad/issues/5053

## Help

[QA steps](https://discourse.canonical.com/t/qa-steps/152) - [Commit guidelines](https://discourse.canonical.com/t/commit-guidelines/148)

2022-10-27 10:26 UTC, webteam-app commented
Demo starting at https://ubuntu-com-12235.demos.haus

2022-10-28 13:58 UTC, minkyngkm requested changes
Hi @carkod I still see many duplicated options in select... 

<img width="383" alt="image" src="https://user-images.githubusercontent.com/57550290/198627966-0905806d-1056-4b39-97e9-597a95aab91a.png">

2022-10-28 16:42 UTC, carkod commented
> 

Sorry, didn't pay attention QAeing myself. It should look much better now.

2022-11-01 09:34 UTC, minkyngkm approved these changes
LGTM 👍

2022-11-01 10:02 UTC, merged