Refresh /iot/intel-iotg
canonical/ubuntu.com pull request #12255
Opened 2022-11-04 11:05 UTC by petesfrench

## Done

- Refresh /tio/intel-itog based on [copydoc](https://docs.google.com/document/d/1hxKzPs6e6JQaa9tBqfZ55GAXrVnEryEWBja8HlXy-lc/edit#)

## QA

- Go to /iot/intel-iotg and compare against the copydoc
- Check each link in the table of downloads

## Issue / Card

Fixes https://github.com/canonical/web-squad/issues/6128

2022-11-04 11:05 UTC, webteam-app commented
Demo starting at https://ubuntu-com-12255.demos.haus

2022-11-07 10:24 UTC, spencerbygraves commented
@petesfrench I would try something like the example below. If you could also add a bit of space above "Are you working on a commercial project?" in the second section that would be good. Thanks.

![image](https://user-images.githubusercontent.com/9105999/200287094-61c4a6d6-a68f-4f9b-aaa9-1f951a20f22e.png)

2022-11-07 12:07 UTC, petesfrench commented
Thank you @spencerbygraves, I have made those changes.

Can the sections below all remain left aligned? I know sometimes we alternate.
![image](https://user-images.githubusercontent.com/58276363/200306480-0d915593-c709-44ec-92a4-7b9b00c82e96.png)

2022-11-07 13:43 UTC, spencerbygraves commented
@petesfrench
> Can the sections below all remain left aligned?

I think so, but I'd make the titles h2.

Thanks

2022-11-07 14:55 UTC, sowasred2012 commented
I find the table full of green CTAs overwhelming, like all of them are trying to grab my attention at once. Would something like the first table in this screen still work? ![image](https://user-images.githubusercontent.com/2376968/200340964-abfc4b1b-5b2c-412f-aba4-eb5d64a22d06.png)

@spencerbygraves ^

2022-11-07 15:05 UTC, sowasred2012 requested changes
Couple of minor things, and I'm really not sure about that wall of green CTAs, but looking good otherwise. Was the URL change a request? I don't see where that's documented. We will need to add a redirect.

2022-11-07 15:05 UTC, sowasred2012 commented on templates/download/iot/intel-iot.html
> +        loading="lazy"
Appears above the "fold"

```suggestion
        loading="auto"
```

2022-11-07 15:05 UTC, sowasred2012 commented on templates/download/iot/intel-iot.html
> +        loading="lazy"
Appears above the "fold"

```suggestion
        loading="auto"
```

2022-11-07 15:05 UTC, sowasred2012 commented on templates/download/iot/intel-iot.html
> +        loading="lazy"
Appears above the "fold"

```suggestion
        loading="auto"
```

2022-11-07 15:11 UTC, spencerbygraves commented
@sowasred2012 yeah, I think you're right, white buttons would probably be better.

2022-11-07 16:49 UTC, sowasred2012 approved these changes
code & QA :+1:

2022-11-10 07:10 UTC, marinacastejon commented
@petesfrench looks good to me except one thing, the Intel product names in the table are not the same as in the copy doc, and there is a comment from Felicia about updating them. If what was done in the demo site is the same as what she requested let me know and I'll update the review label, thanks!

2022-11-10 10:07 UTC, petesfrench commented
@marinacastejon This one is ready for re-review

2022-11-10 10:24 UTC, sowasred2012 approved these changes
A couple of a11y improvements, but looks good otherwise.

2022-11-10 10:24 UTC, sowasred2012 commented on templates/download/iot/intel-iot.html
> +          <th></th>
```suggestion
          <th><span class="u-off-screen">Hardware type</span></th>
```

2022-11-10 10:24 UTC, sowasred2012 commented on templates/download/iot/intel-iot.html
> +          <th></th>
```suggestion
          <th><span class="u-off-screen">Hardware type</span></th>
```

2022-11-11 15:27 UTC, marinacastejon commented
LGTM, thanks Pete

2022-11-15 08:19 UTC, merged