Add functionality to unsubscribe button
canonical/ubuntu.com pull request #12288
Opened 2022-11-17 14:00 UTC by petesfrench

## Done

- Add functionality to unsubscribe button
- Small refactor of code

## QA

- Visit subscription-centre at [this url](https://pastebin.canonical.com/p/8JkdySRcjM/) (this is a test user)
- Check the test user already has some checkbox's checked when the page loads. If none are checked, check some and click 'Update preferences'. The page will reload and your chosen checkbox's should be checked.
- Next click the 'Unsubscribe' button, this will open a modal, click the second 'Unsubscribe' button. The page should refresh with all checkbox's unchecked
- You can check [the user on marketo](https://pastebin.canonical.com/p/79WVzZw2tF/) to see that the fields are no empty (the field to look for is called '__prototype_interests_'

## Issue / Card

Fixes https://warthogs.atlassian.net/browse/WD-360

2022-11-17 14:00 UTC, webteam-app commented
Demo starting at https://ubuntu-com-12288.demos.haus

2022-11-18 14:01 UTC, sowasred2012 commented on subscriptions.yaml
>  Harware:
Typo: Harware / Hardware

2022-11-18 14:04 UTC, sowasred2012 reviewed
This works - I think we need some sort of notification to the user that the operation (maybe a general "Your preferences have been successfully updated." message?) completed, it feels odd to submit the form and be returned to the page with no ceremony. @al-bakalova what do you think?

2022-11-21 07:52 UTC, al-bakalova commented
@sowasred2012 @petesfrench Scott, this is a good catch! Please do add a confirmation message! "Your preferences have been successfully updated." sounds good to me. 
I think it also makes sense to redirect the user to ubuntu.com's landing page and not to the empty subscription centre. Maybe in the future we can have a more fancy "Sorry to see you go" designed page but it looks like we are not there yet.

2022-11-22 09:39 UTC, carkod commented
@sowasred2012 can you take another look? Thanks

2022-11-22 11:03 UTC, sowasred2012 requested changes
The notifications need a little more work, currently they sit flush against the top nav. Also, there's a hardcoded 192px top padding on the main content strip, I'm not sure that's necessary.

2022-11-23 08:31 UTC, petesfrench commented on templates/templates/base.html
> +    </div>
@sowasred2012 I have updated the 'update' notification as suggested and it looks a lot cleaner. I put the 'unsubscribe' one on the generic template as we want to redirect to the homepage upon unsubscribing. Another option Alex suggested was to have a dedicated 'Sorry to see you go page', maybe this makes most sense here.

2022-11-23 09:05 UTC, sowasred2012 commented on templates/templates/base.html
> +    </div>
Sounds good - I think a sorry to see you go page could be done in a future version.

2022-11-23 11:28 UTC, sowasred2012 approved these changes
Looks good, just please incorporate the a11y tweak before merging.

2022-11-23 11:28 UTC, sowasred2012 commented on templates/subscription-centre/index.html
> +                <div role="heading" aria-level="1" class="p-accordion__heading">
`aria-level="1"` puts them all at the same level as a `h1`:
```suggestion
                <div role="heading" aria-level="2" class="p-accordion__heading">
```

2022-11-23 13:09 UTC, merged