Fix test-js & lint-ts
canonical/ubuntu.com pull request #12312
Opened 2022-11-24 11:59 UTC by minkyngkm

## Done

- Fix code so `test-js` & `lint-ts` pass.

## QA

- `dotrun lint-ts`
- `dotrun test-js`
- 
## Issue / Card

Fixes https://warthogs.atlassian.net/jira/software/c/projects/WD/boards/801?modal=detail&selectedIssue=WD-464

2022-11-24 11:59 UTC, webteam-app commented
Demo starting at https://ubuntu-com-12312.demos.haus

2022-11-24 13:48 UTC, minkyngkm commented
Hi @albertkol ! line 234 this test "/pro/subscribe logged in purchase" keeps failing. but ` cy.login();` is not working at all in my machine. Could you please take a look at this test by any chance?

2022-12-02 17:46 UTC, albertkol requested changes

2022-12-02 17:46 UTC, albertkol commented on static/js/src/PurchaseModal/PurchaseModal.tsx
> +                isCardValid={isCardValid}
The cypress test seems to be failing due the buy button being disabled despite a valid card being added. 

For as much as I understand. `isCardValid` is set to `false` and I cannot see that status changed. And a result the button never gets enabled.

2022-12-02 17:46 UTC, albertkol commented on static/js/src/PurchaseModal/PurchaseModal.tsx
> +                isCardValid={isCardValid}
`isCardValid` has to check to see if the user has a card already set as part of his customer info and if it exists then have it initialised to true.

At the moment `isCardValid` status get's changed from its default `false` status only if the user edits his details.

2022-12-07 15:18 UTC, albertkol approved these changes
:+1:

2022-12-07 15:22 UTC, merged