change intel logo
canonical/ubuntu.com pull request #12432
Opened 2023-01-17 11:00 UTC by andesol

## Done

- Change logo according to the copy doc

## QA

- Visit demo: 
- See Felicia's comment in the [copy doc](https://docs.google.com/document/d/1nBx1SP3Y10gXX0rZPDaz1Gudy-hWP4XRMUcETyPBldI/edit#heading=h.iqtg6b1bg6rk)
- Check that the logo is the right one

## Issue / Card

Fixes https://github.com/canonical/workplace-engineering-squad/issues/872

2023-01-17 11:00 UTC, webteam-app commented
Demo starting at https://ubuntu-com-12432.demos.haus

2023-01-18 08:48 UTC, petesfrench commented on templates/internet-of-things/index.html
>              height="65",
```suggestion
            height="90",
```

2023-01-18 08:49 UTC, petesfrench requested changes
Can you update the size of this image please, it needs to be a square

2023-01-18 10:17 UTC, petesfrench commented
@andesol There is also a link that needed updating, I have tagged you in the copydoc where

2023-01-18 11:42 UTC, andesol commented
Thanks @petesfrench! Should be ok now

2023-01-18 13:47 UTC, petesfrench approved these changes
LGTM

2023-01-18 13:47 UTC, merged