Create banner for 18-04 eol
canonical/ubuntu.com pull request #12484
Opened 2023-01-31 16:41 UTC by petesfrench

## Done

- Create banner for 18-04 eol based off of [this brief](https://docs.google.com/document/d/1hK4aEt6QIyPy8YHZw3ByEoxtiEj8Fs8lcyDebBrpZqk/edit)

## QA

- Check the banner appears on the pages listed in the brief and /robotics has its own custom banner.

## Issue / Card

Fixes https://warthogs.atlassian.net/browse/WD-1543

2023-01-31 16:41 UTC, webteam-app commented
Demo starting at https://ubuntu-com-12484.demos.haus

2023-01-31 21:18 UTC, anthonydillon requested changes
It looks like the banner only had a single word change. To reduce duplication you could use a single include and pass the word difference as a `with`.

2023-02-01 09:44 UTC, carkod commented
@anthonydillon can you re-review? Thanks

2023-02-01 12:37 UTC, anthonydillon approved these changes
Much better, personally I would set `product="robotics industry"` and simply render the `product` variable to make it easily extendable. LGTM 👍

2023-02-02 09:14 UTC, merged