Apply visual suggestions on /pro page
canonical/ubuntu.com pull request #12494
Opened 2023-02-02 12:07 UTC by minkyngkm

## Done

- Apply visual suggestions on /pro page according to [Figma](https://www.figma.com/file/ZAihKxF2wmj9wvoPSnPKmY/Commercial%3A-Ubuntu-Pro?node-id=3227%3A17378&t=7t0zBSmVPUroFrDB-0)

## QA

- Go to `/pro` page
- Compare page against design
- FYI, in Figma `Ready for development` is the design we are aiming for and `QA` is things that needs to be fixed.

## Issue / Card

Fixes https://warthogs.atlassian.net/jira/software/c/projects/WD/boards/801?modal=detail&selectedIssue=WD-1805

2023-02-02 12:08 UTC, webteam-app commented
Demo starting at https://ubuntu-com-12494.demos.haus

2023-02-17 09:42 UTC, lyubomir-popov commented
@minkyngkm anything blocking this?

2023-02-17 10:53 UTC, abhigyanghosh30 approved these changes

2023-02-17 11:05 UTC, lyubomir-popov requested changes
Some suggestions in the code

2023-02-17 11:05 UTC, lyubomir-popov commented on static/sass/styles.scss
> +  background-color: #f7f7f7;
this should use the correct variable from vanilla

2023-02-17 11:05 UTC, lyubomir-popov commented on static/sass/styles.scss
> +  background-color: #666;
please use the correct variable

2023-02-17 11:05 UTC, lyubomir-popov commented on static/sass/styles.scss
> +    background-color: rgba(217, 217, 217, 0.2);
again, pleaase use the corrct variable 
```suggestion
    background-color: $colors--dark-theme--border-low-contrast;
```

2023-02-17 11:05 UTC, lyubomir-popov commented on static/sass/styles.scss
> +  background-color: #666;
```suggestion
  background-color: $color-mid-dark;
```

2023-02-17 11:05 UTC, lyubomir-popov commented on static/sass/styles.scss
> +    background-color: rgba(217, 217, 217, 0.2);
```suggestion
    background-color: $colors--dark-theme--border-low-contrast;
```

2023-02-17 11:05 UTC, lyubomir-popov commented on static/sass/styles.scss
> +  background-color: #f7f7f7;
```suggestion
  background-color: $color-light;
```

2023-02-17 11:06 UTC, lyubomir-popov commented
The diff here is quite large, has this been rebased?

2023-02-17 11:30 UTC, minkyngkm commented
Thanks @abhigyanghosh30 and @lyubomir-popov for reviewing! Everything mentioned has been addressed. Could you take a final look please @lyubomir-popov before merging? I've also merged the latest commit from main and resolved conflicts. Should be all good now 👍

2023-02-20 11:42 UTC, lyubomir-popov commented
LGTM, +1

2023-02-20 12:14 UTC, merged