potential fix for community member no of machines
canonical/ubuntu.com pull request #12530
Opened 2023-02-10 15:26 UTC by abhigyanghosh30

## Done

- [List of work items including drive-bys - remember to add the why and what of this work.]

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/
    - Be sure to test on mobile, tablet and desktop screen sizes
- [List additional steps to QA the new features or prove the bug has been resolved]

## Issue / Card

Fixes #

## Screenshots

[If relevant, please include a screenshot.]

## Help

[QA steps](https://discourse.canonical.com/t/qa-steps/152) - [Commit guidelines](https://discourse.canonical.com/t/commit-guidelines/148)

2023-02-10 15:26 UTC, webteam-app commented
Demo starting at https://ubuntu-com-12530.demos.haus

2023-02-22 10:47 UTC, albertkol requested changes

2023-02-22 10:47 UTC, albertkol commented on webapp/shop/advantage/views.py
> +                subscription.number_of_machines = 50
Solution seems to work. However, please change it a bit. Don't override the `subscription` here.

Instead please save `lp_user in community_members` as a variable and send it to the `advantage_mapper.get_user_subscriptions`. Please override the number of machines at the end of that function. Still not ideal, but it's a temporary thing anyway.

`user_subscriptions = advantage_mapper.get_user_subscriptions(email)` must return the final shape of the subscriptions.

2023-03-22 13:20 UTC, albertkol submitted a review, later dismissed

2023-03-27 18:20 UTC, jpmartinspt approved these changes

2023-03-27 18:36 UTC, merged