WIP Cloud copy updates
canonical/ubuntu.com pull request #12532
Opened 2023-02-13 10:16 UTC by carkod

## Done

Copy updates for /cloud/ pages

## QA

- Check /cloud/hybrid-cloud against [copy docs](https://docs.google.com/document/d/1oIggNSXR5sfl0Ab35x2NIL7I858I7QdPCUXeQI8IIPc/edit#)
- Check /cloud/multi-cloud against [copy docs](https://docs.google.com/document/d/1nWsDaRiUzaupjKDzu1ZqjlmxHGv2HCgW8oBBEacYFLs/edit#heading=h.6gx8ccowcd3a)
- Check /cloud/private-cloud against [copy docs](https://docs.google.com/document/d/19g24YRYzF5dBpUKI1QzTG7fXKj1z0OvwgFll69dFoOs/edit#heading=h.evj3u5y98j9v)

## Issue / Card

Closes https://warthogs.atlassian.net/browse/WD-1322?atlOrigin=eyJpIjoiYTczMGNmNGY3Yjc0NDc0MGE4YTBmZTgzNzA5ZDMwZWIiLCJwIjoiaiJ9
Closes https://warthogs.atlassian.net/browse/WD-1321?atlOrigin=eyJpIjoiODA4MWZjMjg0YTFiNDA5YWE4N2NkYmFkMjE2ZmE4MTkiLCJwIjoiaiJ9
Closes https://warthogs.atlassian.net/browse/WD-1320?atlOrigin=eyJpIjoiZTYwNzEwZTUwOWIwNDUwYWE5YjJhYzc3NjQ3NGZkNzUiLCJwIjoiaiJ9
Closes https://warthogs.atlassian.net/browse/WD-1320?atlOrigin=eyJpIjoiNzMyODNlYjE0MWY2NDg2YThmOWM0NWQ5MmRlODVkNjgiLCJwIjoiaiJ9

## Screenshots

[If relevant, please include a screenshot.]

## Help

[QA steps](https://discourse.canonical.com/t/qa-steps/152) - [Commit guidelines](https://discourse.canonical.com/t/commit-guidelines/148)

2023-02-13 10:16 UTC, webteam-app commented
Demo starting at https://ubuntu-com-12532.demos.haus

2023-02-15 09:23 UTC, anthonydillon requested changes
Few comments and questions in the code

2023-02-15 09:23 UTC, anthonydillon commented on templates/cloud/hybrid-cloud.html
> +        <p><a href="https://ubuntu.com/openstack/">Learn more about Canonical OpenStack&nbsp;&rsaquo;</a></p>
This link should be relative.

2023-02-15 09:23 UTC, anthonydillon commented on templates/cloud/multi-cloud.html
> +      <p>Multi-cloud (also referred to as multi cloud or multi-cloud) is a concept that refers to using multiple <a href="/engage/multi-cloud-business-guide">clouds</a> from more than one cloud servi
I would suggest updating the link to cover "using multiple clouds".

2023-02-15 09:23 UTC, anthonydillon commented on templates/cloud/multi-cloud.html
> +        <p><a href="https://ubuntu.com/openstack/">Learn more about Canonical OpenStack&nbsp;&rsaquo;</a></p>
This link should be relative.

2023-02-15 09:23 UTC, anthonydillon commented on templates/cloud/multi-cloud.html
> +      <h2 class="u-sv2">All you need for your hybrid cloud</h2>
We use multi-cloud above and use hybrid cloud here. Are they the same?

2023-02-15 09:31 UTC, carkod commented
Blocked by https://warthogs.atlassian.net/browse/WD-1315

2023-02-24 09:44 UTC, anthonydillon approved these changes
LGTM :+1:

2023-02-24 09:45 UTC, merged