Add page for Apache Spark solution offer
canonical/ubuntu.com pull request #12552
Opened 2023-02-17 07:36 UTC by grobbie

## Done

- driveby: Correction to scope of Apache Kafka offer
- feature: New page for Apache Spark offer
- feature: Contact form for Apache Spark offer
- feature: integration contact form / page / marketo
- note: adjusted copydoc to change one of the images which was using the old logo. Substituted the image in the page and the copydoc. 

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/
    - Be sure to test on mobile, tablet and desktop screen sizes

## Issue / Card

https://warthogs.atlassian.net/browse/DATAPM-713

## Screenshots

Sorry no screenshot, but you can run `./run` and navigate to `/data/spark` to review

2023-02-17 07:36 UTC, webteam-app commented
Demo starting at https://ubuntu-com-12552.demos.haus

2023-02-17 13:20 UTC, mtruj013 requested changes
Thanks @grobbie! Some comments in the code. Could you please also link to the correct copy doc at the top of the kafka template? It still links to the old one (which you can feel free to delete by the way, since we already have an up to date version in the correct location)

2023-02-17 13:20 UTC, mtruj013 commented on templates/data/spark/index.html
> +      <h1>Accelerate AI/ML innovation anywhere with Apache Spark®</h1>
```suggestion
      <h1>Accelerate AI/ML innovation anywhere with Apache Spark&reg;</h1>
```

2023-02-17 13:20 UTC, mtruj013 commented on templates/data/spark/index.html
> +      <h2>Everything you need to run Spark®</h2>
```suggestion
      <h2>Everything you need to run Spark&reg;</h2>
```

2023-02-17 13:20 UTC, mtruj013 commented on templates/data/spark/index.html
> +      <p>Get 24/7 cover wherever you run your operations - run behind the firewall in your own data centre, or on the cloud – with a fully integrated, supported solution for Apache Spark® from Canoni
```suggestion
      <p>Get 24/7 cover wherever you run your operations &ndash; run behind the firewall in your own data centre, or on the cloud &mdash; with a fully integrated, supported solution for Apache Spark&reg; from Canonical.</p>
```

2023-02-17 13:20 UTC, mtruj013 commented on templates/data/spark/index.html
> +        Canonical’s complete, integrated and fully supported open source solution for data engineering and machine learning at scale.
```suggestion
        Canonical's complete, integrated and fully supported open source solution for data engineering and machine learning at scale.
```

2023-02-17 13:20 UTC, mtruj013 commented on templates/data/spark/index.html
> +        <li>A complete, integrated, full-stack solution for Apache Spark®</li>
```suggestion
        <li>A complete, integrated, full-stack solution for Apache Spark&reg;</li>
```

2023-02-17 13:20 UTC, mtruj013 commented on templates/data/spark/index.html
> +      <p>Rapidly deploy your Apache Spark® applications with the integrated, full stack solution from Canonical.</p>
```suggestion
      <p>Rapidly deploy your Apache Spark&reg; applications with the integrated, full stack solution from Canonical.</p>
```

2023-02-17 13:20 UTC, mtruj013 commented on templates/data/spark/index.html
> +      <h2>The best choice for Apache Spark®, anywhere</h2>
```suggestion
      <h2>The best choice for Apache Spark&reg;, anywhere</h2>
```

2023-02-17 13:20 UTC, mtruj013 commented on templates/data/spark/index.html
> +      <p>Canonical’s scalable and comprehensive full stack system for Apache Spark covers:</p>
```suggestion
      <p>Canonical's scalable and comprehensive full stack system for Apache Spark covers:</p>
```

2023-02-17 13:20 UTC, mtruj013 commented on templates/data/spark/index.html
> +        <li>Integrated solution on Charmed Kubernetes, Azure, and AWS.</li>
Please adjust the indentation here so it aligns with the rest of the list elements

2023-02-17 13:20 UTC, mtruj013 commented on templates/data/spark/index.html
> +      <p>Apache®, Apache Spark, Spark®, and the Spark logo are either registered trademarks or trademarks of the Apache Software Foundation in the United States and/or other countries.</p>
```suggestion
      <p>Apache&reg;, Apache Spark, Spark&reg;, and the Spark logo are either registered trademarks or trademarks of the Apache Software Foundation in the United States and/or other countries.</p>
```

2023-02-17 14:14 UTC, lyubomir-popov commented
Hi, this page is mostly consistent with other pages on the site. I noticed a few small things:

- [ ] the registered marks need to be superscript, in all cases where they appear

![image](https://user-images.githubusercontent.com/2741678/219678227-7c996e35-d26e-4d7b-8984-806673ef1069.png)

Can we please style the following as an h4: (`.p-heading--4`)
- [ ] "Everything you need to run Spark®" 
- [ ] ![image](https://user-images.githubusercontent.com/2741678/219678803-138a9fb6-4d43-496f-8721-0915eacdf602.png)

2023-02-20 11:44 UTC, mtruj013 approved these changes
Thanks @grobbie! LGTM 👍🏻

2023-02-20 11:44 UTC, merged