Added new product card
canonical/ubuntu.com pull request #12718
Opened 2023-03-27 08:58 UTC by julia-queen

## Done

- Added a new product card _ubuntu_18.04_end_of_support for pages with the tag "ubuntu 18.04"

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/
    - Be sure to test on mobile, tablet and desktop screen sizes
- [List additional steps to QA the new features or prove the bug has been resolved]

## Issue / Card

Fixes #

## Screenshots

[If relevant, please include a screenshot.]

## Help

[QA steps](https://discourse.canonical.com/t/qa-steps/152) - [Commit guidelines](https://discourse.canonical.com/t/commit-guidelines/148)

2023-03-27 08:58 UTC, webteam-app commented
Demo starting at https://ubuntu-com-12718.demos.haus

2023-03-28 16:04 UTC, tbille commented
@julia-queen I am not really familiar with this part of the site. Where should I look for in demo: https://ubuntu-com-12718.demos.haus/

2023-04-13 09:50 UTC, julia-queen commented
Hi @tbille ! Any blockers on this request?

2023-04-28 09:18 UTC, caldav requested changes
Proposed a new link since we now have the /18-04 page live. Other than that looking good! Will approve once the suggestions are applied.

2023-04-28 09:18 UTC, caldav commented on templates/blog/product-cards/_ubuntu_18.04_end_of_support.html
> +      <a href="/18-04-end-of-standard-support">Time to prepare for Ubuntu 18.04 LTS End of Standard Support</a>
```suggestion
      <a href="/18-04">Time to prepare for Ubuntu 18.04 LTS End of Standard Support</a>
```

2023-04-28 09:18 UTC, caldav commented on templates/blog/product-cards/_ubuntu_18.04_end_of_support.html
> +    <p><a href="/18-04-end-of-standard-support">Learn more&nbsp;&rsaquo;</a></p>
```suggestion
    <p><a href="/18-04">Learn more&nbsp;&rsaquo;</a></p>
```

2023-04-28 09:21 UTC, caldav approved these changes
:+1:

2023-04-28 09:48 UTC, merged