(feat) /data/docs landing page and discourse integration (DATAPM-785)
canonical/ubuntu.com pull request #12788
Opened 2023-04-13 11:09 UTC by grobbie

## Done

- Add initial /data/docs landing page
- Add integration with charmhub discourse for charmed spark, mongodb and postgres documentation
- (driveby) fix Spark page layout
- Fix branding on Kafka page to align with /data/docs and current Data Fabric branding

## Issue / Card

Fixes DATAPM-785

## Screenshots

![image](https://user-images.githubusercontent.com/3254480/231740760-12fcd424-64e8-4070-8834-08d0e9013b79.png)
![image](https://user-images.githubusercontent.com/3254480/231740797-96b75459-1235-4519-ab45-4a7a30448781.png)

2023-04-13 11:09 UTC, webteam-app commented
Demo starting at https://ubuntu-com-12788.demos.haus

2023-04-13 14:04 UTC, anthonydillon requested changes
Thanks for the proposal @grobbie. I have a few comments in the code and a QA issue.

## QA
- Visiting the docs pages results in 500 for me on the demo: https://ubuntu-com-12788.demos.haus/data/docs/mongodb-vm

2023-04-13 14:04 UTC, anthonydillon commented on templates/data/docs/index.html
> +<section class="p-strip--light">
```suggestion
<section class="p-strip">
```

2023-04-14 08:19 UTC, grobbie commented on templates/data/docs/index.html
> +    <div class="col7">
effected

2023-04-14 08:19 UTC, grobbie commented on templates/data/spark/index.html
> +            loading="auto|lazy"
effected

2023-04-14 08:19 UTC, grobbie commented on templates/data/spark/index.html
> -    </div>
this is now done

2023-04-14 08:19 UTC, grobbie commented on templates/data/docs/index.html
> +<section class="p-strip--light">
ok done

2023-04-14 12:02 UTC, carkod commented
Because we never had docs pulled from charmhub, I think the Python module is not getting the keys in our deployed environments (prod and demos) @grobbie Can you add the following to the [konf file](https://github.com/canonical/ubuntu.com/blob/main/konf/site.yaml#L28)

```
- name: CHARMHUB_DISCOURSE_API_KEY
    secretKeyRef:
      key: charmhub-api-key
      name: discourse-api

  - name: CHARMHUB_DISCOURSE_API_USERNAME
    secretKeyRef:
      key: charmhub-api-username
      name: discourse-api
```
And that should match with the API KEY variables that you've provided.
Thanks

2023-04-17 17:12 UTC, closed without merging