WD-3110 build `/18-04/gcp`
canonical/ubuntu.com pull request #12802
Opened 2023-04-18 09:19 UTC by pedoch

## Done

- Build the `/18-04/gcp` page

## QA

- Check out the [demo here](url) and compare it with the [copy doc](https://docs.google.com/document/d/1d62l-BdsgXjs0PZ_JuxJ0u_xG7lUNqyFVBN-lCvSt00/edit#) and with the [Azure page](url) for design review.

## Issue / Card

- [WD-3110](https://warthogs.atlassian.net/browse/WD-3110)

## Help

[QA steps](https://discourse.canonical.com/t/qa-steps/152) - [Commit guidelines](https://discourse.canonical.com/t/commit-guidelines/148)

2023-04-18 09:19 UTC, webteam-app commented
Demo starting at https://ubuntu-com-12802.demos.haus

2023-04-19 07:57 UTC, juanruitina commented
Some comments:

- Under "What are your options?" there are two CTA buttons in the copy doc that show up in the demo as links. Can you please change this? (I've asked Hugo to confirm that he is fine with the second one being a default/white button).
- This link "[more information on Upgrading to Ubuntu Pro below](https://docs.google.com/document/d/1d62l-BdsgXjs0PZ_JuxJ0u_xG7lUNqyFVBN-lCvSt00/edit#bookmark=id.de99h0no3f6y)." heads to the Google doc instead of to the section in the page, can you tweak?
- I see we refer to the bubble in the meganav (under the Ubuntu logo) as "18-04" instead of "18.04". Can we fix this?

2023-04-19 17:04 UTC, mtruj013 requested changes
Thanks @pedoch ! A few comments in the code:

2023-04-19 17:04 UTC, mtruj013 commented on templates/18-04/gcp.html
> +            <li class="p-list__item has-bullet">MySQL - 5.7</li>
```suggestion
            <li class="p-list__item has-bullet">MySQL &ndash; 5.7</li>
```

2023-04-19 17:04 UTC, mtruj013 commented on templates/18-04/gcp.html
> +            <li class="p-list__item has-bullet">Python - 2.7</li>
```suggestion
            <li class="p-list__item has-bullet">Python &ndash; 2.7</li>
```

2023-04-19 17:04 UTC, mtruj013 commented on templates/18-04/gcp.html
> +            <li class="p-list__item has-bullet">PostgreSQL - 10</li>
```suggestion
            <li class="p-list__item has-bullet">PostgreSQL &ndash; 10</li>
```

2023-04-19 17:04 UTC, mtruj013 commented on templates/18-04/gcp.html
> +            <li class="p-list__item has-bullet">Nodejs - 8.10</li>
```suggestion
            <li class="p-list__item has-bullet">Nodejs &ndash; 8.10</li>
```

2023-04-19 17:04 UTC, mtruj013 commented on templates/18-04/gcp.html
> +            <li class="p-list__item has-bullet">PHP - 7.2</li>
```suggestion
            <li class="p-list__item has-bullet">PHP &ndash; 7.2</li>
```

2023-04-19 17:04 UTC, mtruj013 commented on templates/18-04/gcp.html
> +            <li class="p-list__item has-bullet">ROS - Melodic</li>
```suggestion
            <li class="p-list__item has-bullet">ROS &ndash; Melodic</li>
```

2023-04-20 07:48 UTC, pedoch commented on templates/18-04/gcp.html
> +<section class="p-strip is-deep">
Uh no, the new strip doesn't follow the new design. This is what is on `/18-04` (which Lyubo said I should use) as a guide.

2023-04-20 07:52 UTC, pedoch commented
@mtruj013 could you take another look?

2023-04-20 09:39 UTC, juanruitina commented
Minor tweaks to those two buttons:

* Please swap them, "In place upgrade" should come first (colour is correct)
* Remove "for" in  "[Get started with Ubuntu Pro for 18.04 LTS](https://ubuntu-com-12802.demos.haus/gcp/pro)" to avoid line break in mobile (it also seems more consistent wording)
* Spacing between them is a bit weird in relation with the text above. Maybe just place both buttons on the same paragraph, it seems to do the trick and they will still be stacked.

2023-04-20 12:11 UTC, mtruj013 approved these changes
LGTM

2023-04-21 07:09 UTC, juanruitina commented
UX +1. (I base this mostly on consistency with the other 18.04 pages, that went live without a UX review)

2023-04-24 09:43 UTC, merged