[copy update] WD-3499 `/managed/apps/kafka` contact link update
canonical/ubuntu.com pull request #12857
Opened 2023-05-10 16:12 UTC by pedoch

## Done

- Updated Contact Us links on the page

## QA

- Check out the demo here and compare it with the changes requested in the [copy doc](https://docs.google.com/document/d/15c89-PyMc-QnSHglG1hf_Tub5lMkEcVYALL0rm5-LvA/edit#).

## Issue / Card

- [WD-3499](https://warthogs.atlassian.net/browse/WD-3499)

## Help

[QA steps](https://discourse.canonical.com/t/qa-steps/152) - [Commit guidelines](https://discourse.canonical.com/t/commit-guidelines/148)

2023-05-10 16:12 UTC, webteam-app commented
Demo starting at https://ubuntu-com-12857.demos.haus

2023-05-11 15:19 UTC, petesfrench reviewed
I have a couple thoughts on this. I think it would be better to just include the same contact form from `/data/kafka` and use the same form ID on this page, rather than redirecting to another page.
I also wonder if the reason why no one is filling out this page's form is because the buttons are missing the class 'js-invoke-modal', which allows the modal to function properly.

2023-05-14 12:08 UTC, petesfrench commented
@pedoch Did you hear something back from Rob on this?

2023-05-14 15:08 UTC, pedoch commented
@petesfrench Yes, I had a conversation with him and already worked on the changes based on our discussion. I haven't pushed yet because I found something which I need his input on. I intend to reach out to him again on Monday so that I can finalise it.

2023-05-16 13:25 UTC, petesfrench requested changes
There is another contact-form at the bottom of the page that has a different form ID so will be routed differently, is this what was requested? In most cases it makes more sense to use the same formid (and usually the same form) throughout the page

2023-05-16 13:25 UTC, petesfrench commented on templates/managed/apps/kafka.html
> +          <p><a href="#get-in-touch" class="p-button--positive js-invoke-modal">Contact us</a></p>
```suggestion
          <p><a href="/managed/contact-us" class="p-button--positive js-invoke-modal">Contact us</a></p>
```

2023-05-16 16:42 UTC, petesfrench commented
@pedoch Yep, sounds good! And updating the links in the doc would be good also, but really could be done by Rob.
I still think we should update the contact-us to link to the same modal as the others.

2023-05-16 17:27 UTC, pedoch commented
@petesfrench what exactly do you mean when you say "we should update the contact-us to link to the same modal as the others"? I'm not sure I follow.

2023-05-16 19:28 UTC, petesfrench commented
@pedoch the form at the very bottom of the page: 
![image](https://github.com/canonical/ubuntu.com/assets/58276363/92ebc7e0-ab98-4997-8258-fd46fa6744fa)

2023-05-17 08:04 UTC, pedoch commented
@petesfrench I see what you mean. Yes, that should be included, pushing now.

2023-05-18 18:22 UTC, pedoch commented
@petesfrench you can take a look at this again. The links on the copy doc have been updated too.

2023-05-19 11:58 UTC, petesfrench approved these changes
LGTM

2023-05-19 14:57 UTC, merged