Update chart data on /kernel/lifecycle
canonical/ubuntu.com pull request #12858
Opened 2023-05-11 10:15 UTC by petesfrench

## Done

- Updates chart data on /kernel/lifecycle based on [spreadsheet data](https://docs.google.com/spreadsheets/d/1KIuOAa620yseE0uhIl67u2SlS0bWlPI_d98bvYM2Yl8/edit#gid=281992953)
- Updates `createChart` to use the earliest and latest dates to scale the graph domain

## QA

- Each graph is build of a different tab in the [spreadsheet](https://docs.google.com/spreadsheets/d/1KIuOAa620yseE0uhIl67u2SlS0bWlPI_d98bvYM2Yl8/edit#gid=281992953), compare the data with each graph as follows
[Kernel all](https://docs.google.com/spreadsheets/d/1KIuOAa620yseE0uhIl67u2SlS0bWlPI_d98bvYM2Yl8/edit#gid=703230516) -> `All releases`
[Kernel lts](https://docs.google.com/spreadsheets/d/1KIuOAa620yseE0uhIl67u2SlS0bWlPI_d98bvYM2Yl8/edit#gid=281992953) -> `All LTS Releases`
[Kernel 22.04](https://docs.google.com/spreadsheets/d/1KIuOAa620yseE0uhIl67u2SlS0bWlPI_d98bvYM2Yl8/edit#gid=1844838308) -> `22.04`

## Issue / Card

Fixes https://warthogs.atlassian.net/browse/WD-2248

2023-05-11 10:15 UTC, webteam-app commented
Demo starting at https://ubuntu-com-12858.demos.haus

2023-05-11 10:19 UTC, petesfrench commented
@juanruitina Could you take a look at the graphs in [this demo](https://ubuntu-com-12858.demos.haus/kernel/lifecycle) please. I feel like they are getting a little unruly with the amount of information that show, and for some of the more recent LTS, it is hard to match the name(ex. Ubuntu 20.04.5 LTS (v5.15)) with the bars as they are so far to the right.

2023-05-12 10:46 UTC, juanruitina commented
* Please disable automatic scrolling when switching tabs. It's not necessary, it gets annoying when switching.
* Tabs have a white background and don't play well with the gray page background. @lyubomir-popov can you advise? Shall we just make all sections have a white background?

I'm having a hard time making sense of the data in the chart. Why does "All releases" and "All LTS releases" show the same releases, but with different info for each and with different keys? Isn't "All releases" supposed to show interim releases as well? If HWE is for LTS releases only (as I can infer from the copy), why not drop "All releases" altogether? Why does info under on every LTS in "All LTS releases" and the specific release tabs differ? I would understand these tabs to behave as filters, info should be aligned between them. I see the wireframe in the copy doc referred separately to "release schedule" and "support schedule", maybe it has something to do with this. @EdoardoBarbieriCanonical Maybe you can provide explain?

2023-05-12 11:29 UTC, lyubomir-popov commented
This tabstrip could easily be a side nav - we'll dodge the color background issue, and also the horizontal scrollbar:
![image](https://github.com/canonical/ubuntu.com/assets/2741678/06bc38d4-2ffd-45b1-880f-f87c4706483f)

2023-05-15 20:33 UTC, petesfrench commented
@lyubomir-popov What do you mean by side-navigation? Do you mean like the default [side-navigation](https://vanillaframework.io/docs/patterns/navigation#side-navigation) or a stacked version of the tabs?

2023-05-15 23:48 UTC, petesfrench commented
@lyubomir-popov I had a go at introducing a side navigation with a paper background, but it needs some design input. Can you take a look please?

2023-05-16 00:48 UTC, carkod commented
Quickly glancing, it looks like the "All releases" and "All LTS releases" contain the same data? Maybe UX @juanruitina can suggest removing it?

2023-05-16 13:32 UTC, petesfrench commented
@lyubomir-popov Can you take another look please?

2023-05-17 00:28 UTC, brettgrand commented
@juanruitina @carkod I have no idea why there are so many tabs with the same information.  I would guess its an evolution over time that nobody has bothered to clean up.  Kernel hasn't had a PM since Nikos left and I suspect he was the last one to know these existed, let alone update.  From my perspective I would try to base everything off of the 'Kernel table' tab if possible as that should have everything, and if its missing something then its easier to add there as a single source of truth rather than spread all over the place.

2023-05-17 13:12 UTC, petesfrench commented
@juanruitina @brettgrand The scope of this PR is slowly expanding and I don't want to block this work any longer. Can I suggest we add the missing data @carkod has highlighted and get this merged. 
We can schedule in some time into the roadmap to tackle some of the other issues on this page later down the line.

2023-05-18 08:41 UTC, carkod commented
@juanruitina can you take a look?

2023-05-19 07:31 UTC, juanruitina commented
LGTM! Let's revisit the data later in the cycle as agreed.

2023-05-19 12:56 UTC, petesfrench commented
@mtruj013 Can you take another look please?

2023-05-19 20:32 UTC, mtruj013 requested changes
Thanks @petesfrench! It looks like there are some differences in some of the task names compared to what's on the spreadsheet. QA was fine for the changes on all the pages with tabs :+1:

2023-05-19 20:32 UTC, mtruj013 commented on templates/shared/_kernel-support-schedule.html
> +            <td><strong>Ubuntu 22.04.0 LTS</strong></td>
```suggestion
            <td><strong>Ubuntu 22.04.0 LTS (v5.15)</strong></td>
```
I believe these are all supposed to have the version number as well

2023-05-22 14:22 UTC, petesfrench commented on static/js/src/chart-data.js
> +    taskName: "Ubuntu 22.04.2 LTS (v5.19)",
I think it is better we keep the version number as to align with the rest of the graph data

2023-05-23 07:33 UTC, mtruj013 commented on static/js/src/chart-data.js
> +    taskName: "Ubuntu 22.04.2 LTS (v5.19)",
@petesfrench Sure thing, I flagged it because it's not on the spreadsheet

2023-05-23 07:38 UTC, mtruj013 approved these changes
LGTM!

2023-05-23 08:50 UTC, merged