/download/risc-v redesign
canonical/ubuntu.com pull request #12870
Opened 2023-05-15 15:42 UTC by mtruj013

## Done

- Applied redesign as per [mock-up](https://www.figma.com/file/WsMLgH1TXcU1mZ7YjqZRDY/u.com%2Fdownload%2Frisc-v?type=design&node-id=1-479&t=CjoQFe70UKFQNHyE-0)
- Added functionality for small screen dropdown select

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: https://ubuntu-com-12870.demos.haus/download/risc-v
- Check against design
    - Be sure to test on mobile, tablet and desktop screen sizes

## Issue / Card

Fixes https://warthogs.atlassian.net/browse/WD-3875

2023-05-15 15:42 UTC, webteam-app commented
Demo starting at https://ubuntu-com-12870.demos.haus

2023-05-19 14:10 UTC, petesfrench commented on templates/download/risc-v/tab-6.html
> +    </div>
extra closing div here

2023-05-23 16:03 UTC, mtruj013 commented
@lyubomir-popov @juanruitina whenever y'all have a minute could you take a look?

2023-05-24 16:43 UTC, petesfrench commented on templates/download/risc-v/tab-7.html
>        <hr class="u-no-margin--bottom">
The other tabs don't have a `<hr>` between the buttons and link like appears here

2023-05-24 16:46 UTC, petesfrench commented
![image](https://github.com/canonical/ubuntu.com/assets/58276363/6af72b89-68d6-4516-b437-d1a9295d8cf3)
These buttons looked a little cramped, this is right before the breakpoint changes from large to medium

2023-05-24 16:58 UTC, petesfrench commented on templates/download/risc-v/tab-1.html
> +        loading="lazy"
```suggestion
        loading="auto"
```
As this is visible on page load, we should let it auto load

2023-05-24 17:05 UTC, petesfrench commented on templates/download/risc-v/tab-1.html
> +    <hr class="is-fixed-width col-9">
I think you can remove `.is-fixed-width` on these, I tried removing them and couldn't see any difference

2023-05-24 17:17 UTC, petesfrench commented
The only way to navigate the tab content, is to tab to the bottom of the list. Thus only the last item is accessible
[Screencast from 24-05-23 12:15:55.webm](https://github.com/canonical/ubuntu.com/assets/58276363/60ff64f3-2b1c-4f5a-83bf-be175c3d7445)

2023-05-30 11:00 UTC, lyubomir-popov commented
Only one thing - the images vary in height, which makes the grey area resize a lot. Can we please make them all same height with css, and center them in the available area, both vertically and horizontally? The nset the grey area to an aspect ratio 3(width):2(height). The width should be 10% of the parent, height to match the aspect ratio.

2023-07-10 09:42 UTC, mtruj013 commented on templates/download/risc-v/tab-1.html
> +    <div class="col-6 risc-v-strip is-shallow u-vertically-center u-align--center">
I left it for 2 instances in which it was still needed to match the mock-up spacing, but removed the rest

2023-07-10 09:54 UTC, mtruj013 commented
Thanks @petesfrench @juanruitina and @lyubomir-popov, I believe this is ready for you all to take a look again. 

Few things to mention as discussed during stand-up:

- I've not been able to find a fix for the tab content focus bug. To not hold this up, I'll open a separate ticket.
- I was able to fix the logo sizing issue that I mentioned for tab 3, but please let me know if things still look wonky to you.

2023-07-10 11:27 UTC, juanruitina commented
One minor visual comment: under SiFive Unmatched, the spacing between HRs and the "Ubuntu Server preinstalled image" and "Ubuntu Server live installer" headings is inconsistent (bigger) than under the other tabs. Other than that, this looks good to me, feel free to UX+1 whenever you fix this.

2023-07-11 10:54 UTC, lyubomir-popov commented
I see my comment has been addressed, so +1 from me. Nice work!

2023-07-13 09:24 UTC, anthonydillon requested changes
Looks good @mtruj013 few comments in the code

2023-07-13 09:24 UTC, anthonydillon commented on templates/download/risc-v/tab-2.html
> +<div tabindex="0" role="tabpanel" id="microchip-polarfire-soc-fpga-icicle-kit-tab" aria-labelledby="live-installer" aria-hidden="true">
```suggestion
<div tabindex="0" role="tabpanel" id="microchip-polarfire-soc-fpga-icicle-kit-tab" aria-labelledby="microchip-polarfire-soc-fpga-icicle-kit" aria-hidden="true">
```

2023-07-17 08:15 UTC, mtruj013 commented
Thanks @anthonydillon, could you take a look again?

2023-07-17 10:44 UTC, anthonydillon approved these changes
LGTM thanks for the fixes

2023-07-17 10:57 UTC, merged