[copy update] WD-3785 copy update on `/landscape/pricing`
canonical/ubuntu.com pull request #12878
Opened 2023-05-16 11:23 UTC by pedoch

## Done

- Copy update for `/landscape/pricing`

## QA

- Check out the [demo here](https://ubuntu-com-12878.demos.haus/landscape/pricing) and compare it with the [copy doc](https://docs.google.com/document/d/1pESmRniuiaDHkbzY_60GlOJdCiH2pZ9erI9KV49eDyM/edit#).

## Issue / Card

- [WD-3785](https://warthogs.atlassian.net/browse/WD-3785)

## Help

[QA steps](https://discourse.canonical.com/t/qa-steps/152) - [Commit guidelines](https://discourse.canonical.com/t/commit-guidelines/148)

[WD-3785]: https://warthogs.atlassian.net/browse/WD-3785?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-05-16 11:23 UTC, webteam-app commented
Demo starting at https://ubuntu-com-12878.demos.haus

2023-05-16 13:37 UTC, petesfrench commented
@pedoch I have left a comment in the doc for Rajan, it may result in some changes to the page

2023-05-17 12:34 UTC, petesfrench commented on templates/landscape/pricing.html
> +            <td><a href="#get-in-touch" class="p-button--positive is-dense js-invoke-modal">Get started</a></td>
```suggestion
            <td><a href="/contact-us/form?product=landscape" class="p-button--positive is-dense js-invoke-modal">Get started</a></td>
```
can we keep these as fallbacks in the case that JS is not enabled?

2023-05-17 12:34 UTC, petesfrench commented on templates/landscape/pricing.html
> +            <td><a href="#get-in-touch" class="p-button--positive is-dense js-invoke-modal" data-form-location="/shared/forms/interactive/landscape-managed" data-form-id="5054" data-lp-id="" data-ret
```suggestion
            <td><a href="/contact-us/form?product=landscape" class="p-button--positive is-dense js-invoke-modal" data-form-location="/shared/forms/interactive/landscape-managed" data-form-id="5054" data-lp-id="" data-return-url="/landscape/managed#success" data-lp-url="https://pages.ubuntu.com/things-contact-us.html">Get started</a></td>
```

2023-05-17 12:38 UTC, petesfrench requested changes
Do we need to include the two forms at the top of the table?

2023-05-18 08:17 UTC, pedoch commented
Seems like they were just included, to be part of this update. So I'd say yes.

2023-05-18 19:16 UTC, pedoch commented
@petesfrench the task was updated all changes on the copy doc are going with this PR except the change [https://warthogs.atlassian.net/browse/WD-3792](https://warthogs.atlassian.net/browse/WD-3792) highlighted in this task (which is essentially the contact form/buttons on the Landscape SaaS column).

2023-05-19 11:49 UTC, petesfrench approved these changes
LGTM

2023-05-19 14:55 UTC, merged