WD-3904-credentials-schedule
canonical/ubuntu.com pull request #12988
Opened 2023-06-23 19:47 UTC by abhigyanghosh30

## Done

- [List of work items including drive-bys - remember to add the why and what of this work.]

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/
    - Be sure to test on mobile, tablet and desktop screen sizes
- visit /credentials/schedule?contractItemID=<contractItemID>

## Issue / Card

Fixes # [WD-3904](https://warthogs.atlassian.net/browse/WD-3904)

## Screenshots

![image](https://github.com/canonical/ubuntu.com/assets/30973042/4f504895-b2fc-485f-a927-ca1203c7c8e2)

## Help

[QA steps](https://discourse.canonical.com/t/qa-steps/152) - [Commit guidelines](https://discourse.canonical.com/t/commit-guidelines/148)

2023-06-23 19:47 UTC, webteam-app commented
Demo starting at https://ubuntu-com-12988.demos.haus

2023-06-26 14:26 UTC, camillet16 commented
@abhigyanghosh30 where can I view the demo, demohaus only leads to ubuntu.com when I add the '/credentials/schedule?contractItemID=' it's a 404.

2023-06-26 14:44 UTC, abhigyanghosh30 commented
> @abhigyanghosh30 where can I view the demo, demohaus only leads to ubuntu.com when I add the '/credentials/schedule?contractItemID=' it's a 404.

@camillet16  [Try this link](https://ubuntu-com-12988.demos.haus/credentials/schedule?contractItemID=210)

2023-06-26 15:04 UTC, camillet16 commented on templates/credentials/schedule.html
> +      <h1 style="font-weight: 500">Schedule your exam</h1>
```suggestion
      <h2><strong>Schedule your exam</strong></h2>
      //new branding is currently being updated on canonical.com. This is the pattern they're using at the moment.
```

2023-06-26 15:04 UTC, camillet16 commented on templates/credentials/schedule.html
> +        <label class="p-heading--5" for="exam-date">Select your preferred day</label>
```suggestion
        <label class="p-heading--5 u-no-margin" for="exam-date">Select your preferred day</label>
```

2023-06-26 15:05 UTC, camillet16 commented on templates/credentials/schedule.html
> +        <label class="p-heading--5" for="exam-time">Select your preferred time</label>
```suggestion
        <label class="p-heading--5 u-no-margin" for="exam-time">Select your preferred time</label>
```

2023-06-26 15:14 UTC, camillet16 commented
The background color is #f3f3f3 or $color-paper. thank you!

2023-06-26 20:34 UTC, abhigyanghosh30 commented
> The background color is #f3f3f3 or $color-paper. thank you!

This is for the entire page or the input boxes? Because currently, the input boxes have #f2f2f2 as the default colour.

2023-06-26 20:34 UTC, abhigyanghosh30 commented
> <img alt="Screen Shot 2023-06-26 at 6 09 37 PM" width="378" src="https://user-images.githubusercontent.com/112855834/248847740-fe985cc9-7e51-45b4-94dd-38cbf4ac211e.png">
> * margin-bottom: 1.5rem on top of the 1.2 rem of the `<select>`
> 
> This increases the separation between the selections and the next label. It would total 2.7rem.

Does this apply to all the input sections?

2023-06-27 07:37 UTC, camillet16 commented
> > The background color is #f3f3f3 or $color-paper. thank you!
> 
> This is for the entire page or the input boxes? Because currently, the input boxes have #f2f2f2 as the default colour.

The input box color with paper background is adjusted to rgba(0,0,0,.04)

2023-06-27 07:37 UTC, camillet16 commented
> Does the 2.7rem margin apply to all the input sections?

Yes 😄

2023-06-27 16:39 UTC, mrgnr commented on templates/credentials/schedule.html
> +      <h2><strong>Schedule your exam</strong></h2>
This should be `h1` to follow accessibility standards. You can add `class="p-heading--2"` to style it as an `h2`.

2023-06-27 17:34 UTC, mrgnr approved these changes

2023-06-28 07:56 UTC, abhigyanghosh30 commented
@camillet16 made changes as requested. Please review again

2023-07-21 10:16 UTC, albertkol requested changes

2023-07-21 10:16 UTC, albertkol commented on static/sass/styles.scss
> +
CSS is broken.

2023-07-21 10:16 UTC, albertkol commented on static/sass/styles.scss
> +
It might fix all the failing pipelines and if design is happy then we can try an merge it today.

2023-07-26 12:39 UTC, albertkol approved these changes

2023-07-26 12:40 UTC, merged