Add pages to install and manage lxd
canonical/ubuntu.com pull request #12998
Opened 2023-06-29 17:04 UTC by edlerd

## Done

- added lxd/install and lxd/manage pages

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/
    - Be sure to test on mobile, tablet and desktop screen sizes
- check /lxd, /lxd/install and /lxd/manage

## Issue / Card

Fixes WD-4823

2023-06-30 13:59 UTC, anthonydillon requested changes
Few absolute paths that should be relative.

2023-06-30 13:59 UTC, anthonydillon commented on navigation.yaml
> +      path: https://documentation.ubuntu.com/lxd/
This is still private it looks like

2023-06-30 13:59 UTC, anthonydillon commented on templates/appliance/lxd/_next-steps.html
> +          And you're away. For more information check out the <a href="https://ubuntu.com/lxd">LXD website</a> or read our <a href="https://discuss.linuxcontainers.org/t/lxd-cluster-on-raspberry-pi-4
```suggestion
          And you're away. For more information check out the <a href="/lxd">LXD website</a> or read our <a href="https://discuss.linuxcontainers.org/t/lxd-cluster-on-raspberry-pi-4/9076">tutorial on turning the LXD Ubuntu Appliance into your own homelab</a>.
```

2023-06-30 13:59 UTC, anthonydillon commented on templates/kubernetes/charmed-k8s.html
> +        <p><a href="https://ubuntu.com/lxd">Visit the LXD website&nbsp;&rsaquo;</a></p>
```suggestion
        <p><a href="/lxd">Visit the LXD website&nbsp;&rsaquo;</a></p>
```

2023-06-30 13:59 UTC, anthonydillon commented on templates/kubernetes/index.html
> +          <a href="https://ubuntu.com/lxd">
```suggestion
          <a href="/lxd">
```

2023-06-30 13:59 UTC, anthonydillon commented on templates/templates/navigation-developer-h.html
> +            <li class="p-inline-list__item"><a href="https://ubuntu.com/lxd">LXD</a></li>
```suggestion
            <li class="p-inline-list__item"><a href="/lxd">LXD</a></li>
```

2023-06-30 14:42 UTC, anthonydillon reviewed
Some QA issues around the HTML validation of /lxd/install.

`<pre>` inside a `<p>` break out of the p and confuses the markup.

2023-06-30 14:48 UTC, edlerd commented on templates/lxd/install.html
> +        <a class="p-button--positive js-invoke-modal" href="/lxd#get-in-touch">Get in touch</a>
replaced with a link to the static contact us form.

2023-06-30 14:48 UTC, edlerd commented on navigation.yaml
> +      path: https://documentation.ubuntu.com/lxd/
replaced with the correct docs link

2023-07-03 12:22 UTC, anthonydillon approved these changes
LGTM with a very small suggestion in the code. Sorry I missed it before.

2023-07-03 12:22 UTC, anthonydillon commented on templates/lxd/manage.html
> +      <p><a href="https://ubuntu.com/blog/lxd_ui">Read more about the current state of the UI and future plans</a></p>
```suggestion
      <p><a href="/blog/lxd_ui">Read more about the current state of the UI and future plans</a></p>
```

2023-07-03 12:22 UTC, anthonydillon commented on templates/lxd/manage.html
> +        url="https://lh4.googleusercontent.com/oURP8ffnOR44PGUCGaTlD1rRtfVN3oBkPxuLpuvvI4vrYt_093UhOiDTwIihUtlfPWTEA_48rMqZL1wB832Pa4I5AppqTl4EHbcTPRf3V-fxFQaae2jdYcA7-ntt-vOl6wgTYl1hi54RTifHPnOgnIY"
Can you put this image on assets please?

2023-07-03 19:04 UTC, anthonydillon approved these changes
LGTM v👍

2023-07-03 19:04 UTC, anthonydillon commented on templates/lxd/manage.html
> +      <p><a href="/blog/lxd_ui">Read more about the current state of the UI and future plans</a></p>
Underscore? 🥴

2023-07-04 17:11 UTC, merged