Wd 3946 dev chiselled ubuntu and net containers
canonical/ubuntu.com pull request #12995
Opened 2023-06-26 16:58 UTC by pedoch

## Done

- Build Chiselled Ubuntu page and contact form
- Drive-bys on `/silicon`

## QA

- Check out the demo here and compare it with [the copy doc](https://docs.google.com/document/d/1fUG2SpbfdVDMAdbe7zfuzzvji4oWm-P18D85V2A3F8c/edit) and [the design](https://www.figma.com/file/Jgq60iLkA1su93S0ilHeY2/23.04-U.com---Chiselled-Ubuntu-and-.NET-containers-(WD-3141)?type=design&node-id=70-770&mode=design&t=ui6ZZ6Y6v4ScBZ25-0) 
  - Be sure to test on mobile, tablet and desktop screen sizes

## Issue / Card

- [WD-3946](https://warthogs.atlassian.net/browse/WD-3946)

## Help

[QA steps](https://discourse.canonical.com/t/qa-steps/152) - [Commit guidelines](https://discourse.canonical.com/t/commit-guidelines/148)

2023-06-26 16:58 UTC, webteam-app commented
Demo starting at https://ubuntu-com-12995.demos.haus

2023-06-26 17:04 UTC, pedoch commented
The Marketo ID for the form isn't available yet

2023-06-27 15:21 UTC, pedoch commented
@juanruitina @camillet16 please take a look when you can. Thanks!

2023-06-27 18:22 UTC, juanruitina commented
Nice job, Ochuko. Some minor comments:

- [ ] In the four-column stats block, please reduce the margin between the % figure and the line below.
- [ ] The stats should be within `p` elements, use heading classes instead.
- [ ] Remove the `u-text--muted p-text--small` classes from the disclaimer below the figures. We agreed on the UX phase to keep this rather prominent for accessibility reasons.
- [ ] The last block ("Get in touch") should have a pure white background.
- [ ] The 24/7 text under the fourth icon (the one under "Bug fixing and troubleshooting") is barely readable. @camillet16  can we either make these bigger or change the icon for one without the text?

Thank you!

2023-07-03 08:13 UTC, pedoch commented
Hey @juanruitina, I fixed all the issues except the first one, which is a result of the Ubuntu typography as well as the default margins and paddings added by Vanilla. I didn't implement any additional space between them. According to the design guidelines, I can't remove the default margins and padding on texts added by Vanilla because it messes up the baseline grid.

As for the last item (the 24/7 text in the image), I've exported a higher resolution of the image, please let me know if this is fine.

2023-07-03 08:32 UTC, juanruitina commented
@camillet16 Can you advise on both the excessive margin below the % and the readability issue with the 24/7 icon?

(I'm afraid the issue with readability has to do with sizing, not so much with resolution)

2023-07-03 15:19 UTC, camillet16 commented
<img width="75" alt="Screen Shot 2023-07-03 at 6 13 12 PM" src="https://github.com/canonical/ubuntu.com/assets/112855834/0291c516-6788-4c23-9c2f-3c873df735c8">

- replace with this svg

![fix](https://github.com/canonical/ubuntu.com/assets/112855834/8e170da1-c473-44d6-af91-914e112999f3)

-------
<img width="1143" alt="Screen Shot 2023-07-03 at 5 10 40 PM" src="https://github.com/canonical/ubuntu.com/assets/112855834/b9d22152-39dd-40f3-8e1a-2d5715c3d372">

- add u-no-margin to both the top and bottom content.

2023-07-04 07:50 UTC, pedoch commented
@camillet16 @juanruitina please take a look.

2023-07-04 08:02 UTC, pedoch commented
@mtruj013 please take a look when you can. Thanks!

2023-07-04 08:34 UTC, camillet16 commented
<img width="1148" alt="Screen Shot 2023-07-04 at 11 31 11 AM" src="https://github.com/canonical/ubuntu.com/assets/112855834/0a4048ed-8bba-4193-9033-5fa3fabd9823">

Add padding-bottom: 1.5rem/24px to paragraph above "Get in touch"

----------

<img width="1148" alt="Screen Shot 2023-07-04 at 11 31 46 AM" src="https://github.com/canonical/ubuntu.com/assets/112855834/68a4c7df-49ed-49b5-a8c7-1636b836473b">

Add padding-bottom: 1.5rem/24px this section.

2023-07-04 12:28 UTC, juanruitina commented
LGTM, nice work!

2023-07-04 15:03 UTC, pedoch commented
@camillet16 everything should be good now

2023-07-04 15:04 UTC, camillet16 commented
LGTM!

2023-07-04 15:54 UTC, mtruj013 requested changes
Thanks @pedoch ! A few comments in the code:

2023-07-04 15:54 UTC, mtruj013 commented on templates/containers/chiselled/dotnet.html
> +      <h2>What is chiselled Ubuntu?</h2>
```suggestion
      <h2>What is chiselled Ubuntu</h2>
```
There's no punctuation on these headings on the doc

2023-07-04 15:54 UTC, mtruj013 commented on templates/containers/chiselled/dotnet.html
> +      <p>In August 2022, we released the <a href="/blog/install-dotnet-on-ubuntu">first set of pre-built chiselled Ubuntu runtime images</a> for the .NET ecosystem in collaboration with Microsoft.</p
Both of these can be deleted, they're in a different section

2023-07-04 15:54 UTC, mtruj013 commented on static/sass/styles.scss
> +.u-data-border--top {
I don't think this is necessary, there's a [vanilla component](https://vanillaframework.io/docs/patterns/rule#highlighted) that does the same thing

2023-07-04 15:54 UTC, mtruj013 commented on templates/containers/chiselled/dotnet.html
> +      <div class="u-data-border--top">
```suggestion
      <div class="p-rule--highlight">
```

2023-07-04 15:54 UTC, mtruj013 commented on templates/containers/chiselled/dotnet.html
> +      <div class="u-data-border--top">
```suggestion
      <div class="p-rule--highlight">
```

2023-07-04 15:54 UTC, mtruj013 commented on templates/containers/chiselled/dotnet.html
> +      <div class="u-data-border--top">
```suggestion
      <div class="p-rule--highlight">
```

2023-07-04 15:54 UTC, mtruj013 commented on templates/containers/chiselled/dotnet.html
> +      <div class="u-data-border--top">
```suggestion
      <div class="p-rule--highlight">
```

2023-07-04 17:42 UTC, pedoch commented
@mtruj013 I've addressed your comments. Please take a look again, when you can.

2023-07-05 08:57 UTC, merged