Initial build of the buyers guide
canonical/ubuntu.com pull request #13036
Opened 2023-07-11 22:53 UTC by anthonydillon

## Done

- Built an interactive page at /automotive/buyers-guide

2023-07-11 22:53 UTC, webteam-app commented
Demo starting at https://ubuntu-com-13036.demos.haus

2023-07-11 22:53 UTC, anthonydillon commented
@lyubomir-popov @juanruitina there is some tidying up to do with the interactions but do you have feedback at this point?

2023-07-12 15:16 UTC, juanruitina commented
If we are zooming in the image on hover of the card, I'd make the whole card clickable. By making the clicking surface bigger, we would also be making the interaction easier. Have we done this earlier? I'm aware of the accessibility challenges of clickable cards, but there are also [ways to make them work](https://inclusive-components.design/cards/).

(There are inconsistencies with the design, but I understand you will be working working on that)

2023-07-12 16:18 UTC, lyubomir-popov commented
I think we should all have a short catchup to discuss in detail, but the first thing that stands out to me is the scroll back up, I think it is a bit disconcerting. Wondering if we can cover the entire window (new view), but I'll need to add a clear close button in order to do that

2023-07-28 16:38 UTC, juanruitina commented
Some more feedback:

@lyubomir-popov and I [did some explorations](https://www.figma.com/file/mQnuVCHip6j8Vlecqgqe2C/RFQ-engage-Automotive?type=design&node-id=1%3A11892&mode=design&t=8EjhbRzWILnFX5OO-1) on the navigation at the top of the sections, adding the title of the guide and a close button so users have an easy way out if they get to the page via a section link such as https://ubuntu-com-13036.demos.haus/automotive/buyers-guide#security. He can further explain.

About the animation on hover: images look like they have a bigger height when hovering.

About the animation on click: I don't have strong opinions about the scroll to top, but if that's the case, I'd perhaps try to make it all a bit smoother, perhaps with a fade-out and fade-in for the content of the page. The way the white background expands to the sides on top of the paper background feels a bit weird to me, but I reckon that won't be a problem when you apply the dark background, or if we use the same background for the home and the sections.

I would change the "Continue reading >" to "Continue reading about compatibility >" etc. to have meaningful, non-repeating links that work well with screen readers.

And very little copy comment: link back on the "Compatibility" page should read "Overview".

2023-08-09 14:32 UTC, anthonydillon commented
@lyubomir-popov @juanruitina I have done some work to align with the design and trying to improve upon the UX points about smoothness and link improvements. Please let me know what you think.

2023-08-09 15:23 UTC, juanruitina commented
Nice improvement!

Give the the popup-like behaviour, I'd keep the scroll position when clicking on the "x" icon, given user might be checking just a couple sections as they scroll.

And I'd make the image not clickable when the section is opened, as there's no change on click.

2023-08-09 15:45 UTC, lyubomir-popov commented
@anthonydillon much better! I agree with @juanruitina, and I noticed a few more things:

### Animation
Clicking on a card still doesn't behave as expected - instead of a smooth transformation of elements from the initial state to the final state, the following seems to be happening:
1. The Hero area of the main page gets a `display: none;`. This leads to the card content jumping to the top of the page in an unexpected way, while the background of the card animates from this new position to fill the width of the screen (slow down the transition to 5 sec to see it)
2. On closing the card, content again jumps, and there's a strange animation where some elements resize to a smaller size, while their children seem left aligned

What should happen is more like this [codepen ](https://codepen.io/GreenSock/pen/JjXqMZK)built with gsap (can we maybe just use the ready made gsap [plugin](https://greensock.com/docs/v3/Plugins/Flip/)?)

### PDF
Can  we please have the pdf like so: (showing the real  pdf, after design feedback):
![image](https://github.com/canonical/ubuntu.com/assets/2741678/198200b6-dffa-4917-91e1-0192b85e6bc8)

### Responsiveness 
Can we please have them 50/50 on small and medium screens too? I'd hide the previous / next h2 titles on small screens and just leave the prev/next words and chevrons to fit the available space: 
![image](https://github.com/canonical/ubuntu.com/assets/2741678/99e7b0c0-396f-4e45-b81b-52fb822e2334)


### Images
On another note, I've selected the final images, @egezeytun will help us purchase them. For now, I've uploaded watermarked placeholders [here ](https://assets.ubuntu.com/manager?tag=rfq-placeholders)

2023-08-11 10:25 UTC, anthonydillon commented
@lyubomir-popov can you provide the PDF image please. I can't find it

2023-08-11 16:25 UTC, anthonydillon commented
@juanruitina @lyubomir-popov I have done another round of improvements and tried to address your points above ^

2023-08-11 16:29 UTC, bartaz commented
BTW, Vanilla 4.2 with support for `is-dark` class on inputs and validation fields is released now.

2023-08-11 17:18 UTC, lyubomir-popov commented
Hi good progress. Can we catchup early next week, we still have to work on the animation (or a fallback if you've lost patience for  that :)

2023-08-17 11:48 UTC, lyubomir-popov commented
much better without the animations! A couple of small things:
- can we use is-dark on the fields, they are available as Bartek mentioned
- can we use a small thumbnail for the white paper as in the design (let me know if you need me to export it)
- maybe we should put the form on it's own in a final slide, to make you see it if you just click on the top headings navigation - what do you think @juanruitina?
- and finally, clicking on the green button shows you the footer, something seems broken there:
![image](https://github.com/canonical/ubuntu.com/assets/2741678/d0b3e362-b8ba-4933-9038-6b35c7b77632)

2023-08-17 14:58 UTC, anthonydillon commented
> this line needs to have is-dark on it I believe (there's an almost invisible black hr betweeen the nav and text underneath):

Done

> can we use is-dark on the fields, they are available as Bartek mentioned

This is not available in `3.14.0`

> can we use a small thumbnail for the white paper as in the design (let me know if you need me to export it)

Done

> and finally, clicking on the green button shows you the footer, something seems broken there:

Done

2023-08-17 14:59 UTC, anthonydillon commented
@lyubomir-popov @juanruitina what do you think?

2023-08-17 15:27 UTC, juanruitina commented
> * maybe we should put the form on it's own in a final slide, to make you see it if you just click on the top headings navigation - what do you think @juanruitina?

I agree, it would feel natural, given the user would have seen all the content at that point.

I think we should also tweak the navigation on mobile a bit: "Automotive OS Buyer's Guide" wraps unnecessarily, and the "Previous" and "Next" links can perhaps be smaller, perhaps H4-like. 

![ubuntu-com-13036 demos haus_automotive_buyers-guide(iPhone SE)](https://github.com/canonical/ubuntu.com/assets/1409729/3b3eaa93-6005-4c02-ba8e-1a91538147ee)

Other than this, it all looks good to me.

2023-08-18 07:52 UTC, lyubomir-popov commented
> @lyubomir-popov can you provide the PDF image please. I can't find it

here 
![image 1](https://github.com/canonical/ubuntu.com/assets/2741678/3196ca02-12cf-49da-98e7-c3094fae2cce)

2023-08-18 07:52 UTC, lyubomir-popov commented
I'll give a +1 for easier merging, most of my comments have been addresed. Thanks @anthonydillon !

2023-08-18 16:33 UTC, anthonydillon commented
All done @juanruitina

2023-08-23 14:52 UTC, petesfrench commented
Should we add a check for if the user has JS enabled and if they don't reveal all the hidden text?

2023-08-23 15:04 UTC, petesfrench commented
@juanruitina the simpler part of my brain wants to click 'next' and is confused when it doesn't do anything:
![image](https://github.com/canonical/ubuntu.com/assets/58276363/687bb8e5-c5e9-41d9-a55a-d55b2c11231b)
also it feels weird when you reach the end of the list and 'next' just takes you back the original page

2023-08-23 15:12 UTC, petesfrench requested changes

2023-08-28 17:29 UTC, anthonydillon commented on templates/automotive/buyers-guide/index.html
> +      <h1><strong>Automotive OS <br class="u-hide--small" />Buyer's Guide</strong></h1>
There doesn't seem to be a change here?

2023-08-28 17:29 UTC, anthonydillon commented on templates/automotive/buyers-guide/_form.html
> +    <h2>Download our buyer's guide</h2>
There doesn't seem to be a change here?

2023-08-28 17:30 UTC, anthonydillon commented on templates/automotive/buyers-guide/_form.html
> +      <form action="/marketo/submit" method="post" id="mktoForm_5356">
This is because the version of Vanilla does not support dark forms yet. Which is out of scope for this PR.

2023-08-28 17:34 UTC, anthonydillon commented on templates/automotive/buyers-guide/_form.html
> +              <input required id="lastName" name="lastName" maxlength="255" type="text" />
Good spot but these fields do not exist in Marketo:
![image](https://github.com/canonical/ubuntu.com/assets/1413534/7c459b54-2ac9-452a-96c4-6e351006cf65)

2023-08-28 17:34 UTC, anthonydillon commented
@petesfrench thanks for the review. I have addressed your points.

2023-08-31 14:04 UTC, lyubomir-popov commented
@anthonydillon I realised the images are a bit big in terms of file size, so re-exported them. The new link is https://assets.ubuntu.com/manager?tag=rfq-images-smaller-filesize

Sorry for the double work!

2023-08-31 14:09 UTC, lyubomir-popov commented
@anthonydillon not sure if I missed these or they are regressions, but I see 2 more things that can be fixed:

is-dark class missing on this hr:
![image](https://github.com/canonical/ubuntu.com/assets/2741678/234a4c66-b1d4-48d1-a66b-18aaf7cddbb8)

can we have a shallow section wrap content above the image, so this space increases (at the moment, the image is too close to the button, and might distract people from clicking it)
![image](https://github.com/canonical/ubuntu.com/assets/2741678/9c04a42a-1b22-43c2-bc63-79d528a921d6)

2023-08-31 14:34 UTC, petesfrench commented on templates/automotive/buyers-guide/_form.html
> +    <h2>Download our buyer's guide</h2>
Sorry, it doesn't appear on github, But the this changes the angled tick to a straight tick ( ' )

2023-08-31 14:40 UTC, petesfrench commented on templates/automotive/buyers-guide/_form.html
> +        loading="auto|lazy"
```suggestion
        loading="auto"
```

2023-08-31 14:42 UTC, petesfrench commented on templates/automotive/buyers-guide/_form.html
> +              <label for="title">Title:</label>
```suggestion
              <label for="title">Job title:</label>
```
Not sure if it matters, but we nearly always use 'Job title' here

2023-08-31 14:44 UTC, petesfrench commented on templates/automotive/buyers-guide/_form.html
> +            </li>
Did the Pdm specify all fields should be required?

2023-08-31 14:52 UTC, petesfrench commented on templates/automotive/buyers-guide/index.html
> +      <a href="#compatibility" class="u-hide-on-reveal">
```suggestion
      <a href="#compatibility" class="u-hide-on-reveal" tabIndex="-1">
```
Currently a screen reader sees this as a link. We don't need it visible, as there is the same link above

2023-08-31 14:52 UTC, petesfrench commented on templates/automotive/buyers-guide/index.html
> +      <a href="#developer-support" class="u-hide-on-reveal">
```suggestion
      <a href="#developer-support" class="u-hide-on-reveal"  tabIndex="-1">
```

2023-08-31 14:52 UTC, petesfrench commented on templates/automotive/buyers-guide/index.html
> +      <a href="#certifications-and-compliance" class="u-hide-on-reveal">
```suggestion
      <a href="#certifications-and-compliance" class="u-hide-on-reveal"  tabIndex="-1">
```

2023-08-31 14:52 UTC, petesfrench commented on templates/automotive/buyers-guide/index.html
> +      <a href="#power-management" class="u-hide-on-reveal">
```suggestion
      <a href="#power-management" class="u-hide-on-reveal"  tabIndex="-1">
```

2023-08-31 14:52 UTC, petesfrench commented on templates/automotive/buyers-guide/index.html
> +      <a href="#open-source" class="u-hide-on-reveal">
```suggestion
      <a href="#open-source" class="u-hide-on-reveal" tabIndex="-1">
```

2023-08-31 14:54 UTC, petesfrench commented on templates/automotive/buyers-guide/index.html
> +  <div class="row">
```suggestion
  <div class="u-fixed-width">
```
We should only use rows when there are contained columns

2023-08-31 14:56 UTC, petesfrench commented on templates/automotive/buyers-guide/index.html
> +    <div class="row u-show-on-reveal">
```suggestion
    <div class="u-fixed-width u-show-on-reveal">
```

2023-08-31 14:58 UTC, petesfrench commented on templates/automotive/buyers-guide/index.html
> +  .feature-section {
'feature section' is a generic name for a  specific style

2023-08-31 14:59 UTC, petesfrench commented on templates/automotive/buyers-guide/index.html
> +  <div class="row">
AFAIK

2023-08-31 17:59 UTC, merged