WD-5114 - Update the legal addresses across the site
canonical/ubuntu.com pull request #13037
Opened 2023-07-12 16:07 UTC by anthonydillon

## Done

- Update the legal addresses across the site

## QA

- Check that the addresses are correctly now pointing to Canonical Group Limited. Our address is 5 New street Square, London, EC4A 3TW, United Kingdom
- And 4th floor, 201 Borough High St. London SE1 1JA, United Kingdom for correspondence 
- Check the odd copy doc matches

## Issue / Card

Fixes https://warthogs.atlassian.net/browse/WD-5114

2023-07-12 16:07 UTC, webteam-app commented
Demo starting at https://ubuntu-com-13037.demos.haus

2023-07-13 17:56 UTC, pedoch requested changes
Nice work on this. Seems like a very repetitive process 😅. Left some comments.

Some of them are about the version date. I'm not sure if those are meant to be updated every time a change is made or if it should just follow the date on the copy doc but I commented on them just incase.

I also left comments about some documents that don't seem to be updated. I'm not sure how that should be handled but just wanted to bring them to your attention.

2023-07-13 17:56 UTC, pedoch commented on templates/legal/data-privacy/newsletter.md
The version date isn't updated.

Also, it seems this file isn't up to date with the copy doc. A couple of sections are missing from the copy doc. But should probably be addressed separately. I noticed it because the address for **Legal, Canonical** was missing.

2023-07-13 17:56 UTC, pedoch commented on templates/legal/data-privacy/partner-portal.md
The "Your right to complain" section here has the old address

2023-07-13 17:56 UTC, pedoch commented on templates/legal/data-privacy/snap-store.md
The "Your right to complain" section here has the old address

2023-07-13 17:56 UTC, pedoch commented on templates/legal/data-privacy/snapcraft-nps.md
The "Your right to complain" section here has the old address

2023-07-13 17:56 UTC, pedoch commented on templates/legal/anbox-cloud-privacy-notice.html
The "Your right to complain" section here has the old address. 

Also, I noticed the copy has an address starting with "5th Floor, Blue Fin Building" from what I can see, it might be an old address.

2023-07-13 17:56 UTC, pedoch commented on templates/legal/data-privacy/online-purchase.md
The "Your right to complain" section here has the old address. 

Also, I noticed the copy has an address starting with "5th Floor, Blue Fin Building" from what I can see, it might be an old address.

2023-07-13 17:56 UTC, pedoch commented on templates/legal/data-privacy/sso.md
> +We are Canonical Group Limited. Our address is 5 New Street Square, London, EC4A 3TW, United Kingdom. You can contact us by post at the address set out in the “right to complain” section, below or by
The version date isn't updated.

The address on the copy doc is the one on "201 Borough High St." and the "set out in the “right to complain” section, below" part isn't added.

Also, it seems there were some updates that weren't implemented, references to Ubuntu One. They should probably be handled in another task.

2023-07-13 17:56 UTC, pedoch commented on templates/legal/data-privacy/survey.md
The "Your right to complain" section here has the old address

2023-07-13 17:56 UTC, pedoch commented on templates/legal/data-privacy/recruitment.html
The version date isn't updated

2023-07-13 17:56 UTC, pedoch commented on templates/legal/data-privacy/online-competitions.md
The version date isn't updated

2023-07-13 17:56 UTC, pedoch commented on templates/legal/data-privacy/esxi.md
The version date isn't updated

2023-07-13 17:56 UTC, pedoch commented on templates/legal/data-privacy/unilateral-nda.md
The version date isn't updated

2023-07-13 17:56 UTC, pedoch commented on templates/legal/data-privacy/user-survey.md
The "Your right to complain" section here has the old address



Also, the copy doc here doesn't seem to be updated at all. Should probably be remedied.

2023-07-13 17:56 UTC, pedoch commented on templates/legal/data-privacy/webinar.md
The doesn't seem to be aligned with the copy doc. Some text isn't complete like set out in the "Your right to complain" section. It's not clear which is the correct/up-to-date version since there are copy updates on the doc that date back to 2019

2023-07-13 17:56 UTC, pedoch commented on templates/legal/motd.html
The "Contact" section here has the old address.
The version date isn't updated

Also, the address on the copy doc isn't updated

2023-07-13 17:56 UTC, pedoch commented on templates/legal/systems-information-notice.html
The "Contact" section here has the old address.
The version date isn't updated

Also, the copy doc here links to the legal folder, rather than the doc itself

2023-07-14 15:31 UTC, anthonydillon commented on templates/legal/data-privacy/recruitment.html
Looks right from the copy doc

2023-07-14 15:39 UTC, anthonydillon commented
@pedoch Thank you for the thorough review. I have addressed your comments and a few copy changes around the place.

2023-07-14 16:43 UTC, pedoch commented on templates/legal/data-privacy/recruitment.html
Yh, I wasn't sure if we should just follow the copy doc or if it should be something updated whenever there's a change. But I decided to bring it to your attention anyway.

2023-07-14 16:47 UTC, pedoch commented on templates/legal/systems-information-notice.html
Looks like this still has the old address.

2023-07-14 16:50 UTC, pedoch commented on templates/legal/motd.html
This still has the old address as well

2023-07-14 17:34 UTC, pedoch commented on templates/legal/motd.html
This still has the old address on the Contact section

2023-07-14 17:48 UTC, pedoch commented on templates/legal/data-privacy/sso.md
> +We are Canonical Group Limited. Our address is 5 New Street Square, London, EC4A 3TW, United Kingdom. You can contact us by post at the address set out in the “right to complain” section, below or by
The wrong address here. The doc says "The Office Group, St Dunstans House, 4th floor, 201 Borough High St, London SE1 1JA", unless that's a mistake

2023-07-14 17:49 UTC, pedoch approved these changes
Thank you @anthonydillon! Just a couple of comments to be addressed but I'm giving a +1 now.

2023-07-20 14:29 UTC, merged