Minor bug fixes
canonical/ubuntu.com pull request #13467
Opened 2024-01-17 13:10 UTC by petesfrench

## Done

Fixes the following QA bugs:
When you navigate to the WSL page on small screens. The Menu no longer works.
When using the navigation go to All Canonical > About and click any of the links such as Blog and none of them work.
If you go to /ai and hit search it's black text if black background.
On small screen, none of the quick links work when clicked.

## QA

- Ensure the above bugs are fixed

## Issue / Card

Fixes https://warthogs.atlassian.net/browse/WD-8295

2024-01-17 13:10 UTC, webteam-app commented
Demo starting at https://ubuntu-com-13467.demos.haus

2024-01-17 13:51 UTC, mtruj013 requested changes
Thanks @petesfrench! Just a couple bugs remaining, and also a question:

- WSL page:
Menu works but it's a bit misaligned with the search icon when compared to the landing page, for example: 
wsl:
![Screenshot from 2024-01-17 14-34-35](https://github.com/canonical/ubuntu.com/assets/17607612/2cdad153-4035-4002-ab5c-b93763cc593d)
vs:
![image](https://github.com/canonical/ubuntu.com/assets/17607612/32d62b72-33e5-4cb9-a58e-d0cc698dc0e7)

- /ai search:
Clicking on the search icon on large screens routes to /search. If you hit the back button you can see the input as shown here:
[Screencast from 17.01.2024 14:41:33.webm](https://github.com/canonical/ubuntu.com/assets/17607612/3cf11832-d366-4b72-9940-f4ed512f08a1)
Doesn't happen on small or medium screens though

- Quick links:
I'm not sure what quick links mean in this context so I'm not sure what to test 😅

2024-01-17 15:41 UTC, petesfrench commented
Thanks @mtruj013! 

The quick links are these links (this example is found under support > resources):
![image](https://github.com/canonical/ubuntu.com/assets/58276363/968167a9-332c-4f2c-bef1-0c1897426c03)

The search icon position is being fixed in a different PR, but thank you for flagging.

2024-01-18 09:06 UTC, mtruj013 approved these changes
LGTM!

2024-01-18 09:21 UTC, merged