WD-8578 - copy update on /support
canonical/ubuntu.com pull request #13524
Opened 2024-02-01 11:45 UTC by lizzochek

## Done

Update /support according to copy doc

## QA
- [demo link](https://ubuntu-com-13523.demos.haus/download/kvm)
- [copy doc](https://docs.google.com/document/d/1AU2dwTXpQk2UuEvSuAqRKrbPWYb-LR0ZGvWu6xw95I8/edit)
- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8001/
- Run through the following [QA steps](https://discourse.canonical.com/t/qa-steps/152)
- Check that the page is correctly updated according to copy doc

## Issue / Card
[WD-8578](https://warthogs.atlassian.net/browse/WD-8578)

Fixes #

## Screenshots

2024-02-01 11:45 UTC, webteam-app commented
Demo starting at https://ubuntu-com-13524.demos.haus

2024-02-01 20:22 UTC, lorumic approved these changes

2024-02-02 08:18 UTC, akbarkz requested changes
@lizzochek I noticed you changed a layout of this part of the page:
![Screenshot 2024-02-02 at 14 17 15](https://github.com/canonical/ubuntu.com/assets/15943863/1a542afc-9f50-40a5-a8aa-b26f7162d9f1)

According to design it should look different: https://www.figma.com/file/YdmmtZxcCdEVJE4JmSqfeD/Ubuntu.com%2Fsupport?type=design&node-id=96-2783&mode=design&t=6eczyevgm5mdxDgj-4

2024-02-02 11:48 UTC, lizzochek commented
@akbarkz updated, please check. Demo will be ready in a minute

2024-02-02 11:53 UTC, akbarkz approved these changes

2024-02-02 11:54 UTC, merged