Add product cards
canonical/ubuntu.com pull request #13772
Opened 2024-04-18 18:08 UTC by julia-queen

## Done

- Add product cards:

1. templates/blog/product-cards/_ai-solutions.html
2. templates/blog/product-cards/_ceph.html
3. templates/blog/product-cards/_charmed_mongodb.html
4. templates/blog/product-cards/_desktop_ubuntu-desktop-for-organisations.html
5. templates/blog/product-cards/_desktop_ubuntu-for-desktops.html
6. templates/blog/product-cards/_infrastructure_maximise-your-cloud-infrastructure.html
7. templates/blog/product-cards/_infrastructure_optimised-costs-across-any-cloud.html
8. templates/blog/product-cards/_kubernetes.html
9. templates/blog/product-cards/_lxd.html
10. templates/blog/product-cards/_microcloud.html
11. templates/blog/product-cards/_opensearch.html
12. templates/blog/product-cards/_openstack.html
13. templates/blog/product-cards/_server_scale-out-with-ubuntu-server.html
14. templates/blog/product-cards/_wsl_ubuntu-on-windows.html

- Remove an outdated card from rotation
- Update legacy part:

templates/blog/product-cards.html

## QA

- Go to blog page and check if a card appears on the right side, the links are not broken and images (if any) are sized accordingly 

1. https://ubuntu-com-13739.demos.haus/blog/what-is-mlflow
2. https://ubuntu-com-13739.demos.haus/blog/secure-data-storage-ai
3. https://ubuntu-com-13739.demos.haus/blog/open-source-cloud
4. https://ubuntu-com-13739.demos.haus/blog/mongodb-usecase-financialservices
5. https://ubuntu-com-13739.demos.haus/blog/opensearchcon-canonical-2023
6. https://ubuntu-com-13739.demos.haus/blog/edge-computing-examples
7. https://ubuntu-com-13739.demos.haus/blog/lxd_5-21-0_lts
8. https://ubuntu-com-13739.demos.haus/blog/sbi-group-unlocks-infrastructure-automation-with-secure-on-premises-openstack-cloud
9. https://ubuntu-com-13739.demos.haus/blog/the-coronation-of-a-new-mascot-noble-numbat
10. https://ubuntu-com-13739.demos.haus/blog/introducing-netplan-v1
11. https://ubuntu-com-13739.demos.haus/blog/improved-testing-ubuntu-wsl
12. https://ubuntu-com-13739.demos.haus/blog/ubuntu-compliance-monitoring-with-microsoft-intune

## Issue / Card

Fixes # https://warthogs.atlassian.net/browse/GROWENG-3389
Fixes # https://warthogs.atlassian.net/browse/GROWENG-3335
Fixes # https://warthogs.atlassian.net/browse/GROWENG-3334
Fixes # https://warthogs.atlassian.net/browse/GROWENG-3331
Fixes # https://warthogs.atlassian.net/browse/GROWENG-3330
Fixes # https://warthogs.atlassian.net/browse/GROWENG-3328
Fixes # https://warthogs.atlassian.net/browse/GROWENG-3074

## Screenshots

[If relevant, please include a screenshot.]

## Help

[QA steps](https://discourse.canonical.com/t/qa-steps/152) - [Commit guidelines](https://discourse.canonical.com/t/commit-guidelines/148)

2024-04-18 18:08 UTC, webteam-app commented
julia-queen is not a collaborator of the repo

2024-04-23 09:45 UTC, julia-queen commented
@caldav will take the ownership of this PR if it's not merged before the end of the week. I allowed edits and access to secrets by maintainers

2024-09-24 08:17 UTC, immortalcodes commented
Hey @julia-queen @caldav , could you please look into the demo, it's not working

2024-09-24 08:41 UTC, mtruj013 commented
@immortalcodes demo here: https://ubuntu-com-13772.demos.haus/

2024-09-24 11:18 UTC, immortalcodes requested changes
Hey, thanks for the PR.
I have left a couple of comments regarding alt text, hr tags and em dash.
Please try to fix those for all the pages in the PR.

2024-09-24 11:18 UTC, immortalcodes commented on templates/blog/product-cards/_desktop_ubuntu-desktop-for-organisations.html
> +    <hr class="u-sv1" />
With the latest vanilla version we either have `p-rule` or `p-rule--muted` class with `<hr>` tags. Could you please amend this for all hr tags in the PR

2024-09-24 11:18 UTC, immortalcodes commented on templates/blog/product-cards/_desktop_ubuntu-desktop-for-organisations.html
> +         alt="ubuntu logo" />
We do not add "logo" word to mention it's logo. Just leaving out the name will be good enough

2024-09-24 11:18 UTC, immortalcodes commented on templates/blog/product-cards/_desktop_ubuntu-desktop-for-organisations.html
> +         alt="ubuntu logo" />
Please refer [here](https://docs.google.com/document/d/12nLPp3ktElJCNl_i3q5fGOjWMPhPXXFsIJGH-AuxduQ/edit) for all alt="" related info

2024-09-24 11:18 UTC, immortalcodes commented on templates/blog/product-cards/_ai-solutions.html
> +         alt="canonical ai ml illustration" />
It might not require an alt="" here. Please refer the doc I had pinned in one of comments.

2024-09-24 11:18 UTC, immortalcodes commented on templates/blog/product-cards/_infrastructure_maximise-your-cloud-infrastructure.html
> +        Canonical lets you take control of your cloud, cutting costs and easily mixing private and public cloud platforms – all with a 10-year security guarantee.
Please add a `emdash` here

2024-09-24 11:18 UTC, immortalcodes commented on templates/blog/product-cards/_lxd.html
> +        LXD brings flexible resource limits, advanced snapshot and networking support, and better security – all making for easier, leaner and more robust containerised solutions and VMs.
```suggestion
        LXD brings flexible resource limits, advanced snapshot and networking support, and better security &mdash all making for easier, leaner and more robust containerised solutions and VMs.
```

2024-09-24 11:18 UTC, immortalcodes commented on templates/blog/product-cards/_openstack.html
> +        OpenStack and Ubuntu bring automated deployment and management that help you optimise infrastructure costs – no matter your industry or use case.
&mdash here

2025-03-18 09:33 UTC, closed without merging

2025-03-18 09:33 UTC, muhammad-ali-pk commented
Closing this PR as it is too outdate wrt main.