WD-10785-cred-surface-ta-exams-status-instead-of-resorting-to-mapping
canonical/ubuntu.com pull request #13822
Opened 2024-04-29 09:31 UTC by abhigyanghosh30

## Done

- Surface status for exams directly from TA 
- Handle errors fetching info from TA

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/
    - Be sure to test on mobile, tablet and desktop screen sizes
- Break TA API calls locally
- Visit /credentials/your-pages
  - Check if page still loads 
- Fix TA calls
  - Check if the exam status is the same as TA

## Issue / Card

Fixes #

## Screenshots

[If relevant, please include a screenshot.]

## Help

[QA steps](https://discourse.canonical.com/t/qa-steps/152) - [Commit guidelines](https://discourse.canonical.com/t/commit-guidelines/148)

2024-04-29 09:31 UTC, webteam-app commented
### [<img src='https://assets.ubuntu.com/v1/6baef514-ubuntu-circle-of-friends-large.svg' height=32 width=32> Demo</img>](https://ubuntu-com-13822.demos.haus)
### [<img src='https://assets.ubuntu.com/v1/e512b0e2-jenkins.svg' height=32 width=32> Jenkins </img>](https://jenkins.canonical.com/webteam/job/start-demo/19446)
### [<img src='https://assets.ubuntu.com/v1/7144ec6d-logo-jaas-icon.svg' height=32 width=32> demos.haus </img>](https://demos.haus)

2024-04-30 15:28 UTC, jpmartinspt approved these changes

2024-04-30 15:34 UTC, jpmartinspt requested changes
The exams that can still be scheduled do not appear up top. Some of the exams that I see as complete in staging, show as "could not find information" now?

2024-04-30 18:40 UTC, abhigyanghosh30 commented
> The exams that can still be scheduled do not appear up top. Some of the exams that I see as complete in staging, show as "could not find information" now?

Moved all such exams to the bottom. I however don't see them in local but they appear in demos.

2024-04-30 20:56 UTC, jpmartinspt approved these changes

2024-05-01 21:52 UTC, merged