Update AWS links
canonical/ubuntu.com pull request #13924
Opened 2024-06-05 13:51 UTC by carkod

## QA

- Go to /aws and [check copy doc comments are addressed](https://docs.google.com/document/d/1lkH-MSPmgjCMP4gI0FW29YIKVDvBuddxA63iQhmsYIU/edit#heading=h.wmtx864far5b)
- Go to /aws/pro and [check copy doc comments are addressed](https://docs.google.com/document/d/1pLRWJZSpE04nYt-yHBtCjxGI7VZsigcP2UJIBmR8i-0/edit)

- View the site locally in your web browser at: http://0.0.0.0:8001/
    - Be sure to test on mobile, tablet and desktop screen sizes
- [List additional steps to QA the new features or prove the bug has been resolved]

## Issue / Card

Fixes https://warthogs.atlassian.net/browse/WD-11844
Fixes https://warthogs.atlassian.net/browse/WD-11846

## Help

[QA steps](https://discourse.canonical.com/t/qa-steps/152) - [Commit guidelines](https://discourse.canonical.com/t/commit-guidelines/148)

2024-06-07 09:32 UTC, britneywwc reviewed
LGTM, there is some link inconsistencies from the copy docs for 24.04 LTS download link, I'll address it in the copy doc.

2024-06-07 09:32 UTC, britneywwc commented on templates/aws/shared/_get_pro.html
> +      <h3 class="p-heading--4"><a href="https://aws.amazon.com/marketplace/pp/prodview-s4zvkzmlirbga">24.04 LTS</a></h3>
```suggestion
      <h3 class="p-heading--4"><a href="https://aws.amazon.com/marketplace/pp/prodview-kbkyvwyqubv2g">24.04 LTS</a></h3>
```
The link is different from the copy doc

2024-06-07 21:47 UTC, carkod commented
> LGTM, there is some link inconsistencies from the copy docs for 24.04 LTS download link, I'll address it in the copy doc.

I believe what I did is actually correct, Carlos Bravo made the mistake. Can I get final review?

2024-06-10 02:28 UTC, britneywwc commented on templates/aws/shared/_get_pro.html
> +      <h3 class="p-heading--4"><a href="https://aws.amazon.com/marketplace/pp/prodview-s4zvkzmlirbga">24.04 LTS</a></h3>
```suggestion
      <h3 class="p-heading--4"><a href="https://aws.amazon.com/marketplace/pp/prodview-kbkyvwyqubv2g">24.04 LTS</a></h3>
```

2024-06-10 02:30 UTC, britneywwc requested changes
Could you please change the link? It should be the other one

2024-06-10 07:41 UTC, britneywwc approved these changes
Looks good, thanks!

2024-06-10 08:21 UTC, merged