Landing page redesign feedback
canonical/ubuntu.com pull request #13955
Opened 2024-06-14 12:05 UTC by mtruj013

## Done

- Applied design changes as outlined on mock-up
- Drive by:
  - Removed unused class on /hpe
  - Ran djlint 
  - Upgraded to latest vanilla (v4.13)

## QA

- View the site locally in your web browser at: https://ubuntu-com-13955.demos.haus/
- Check against [design](https://www.figma.com/design/Le4TTzyOFbcbqTPJ1tVoZT/U.com---Home-and-footer-(rebranding)?node-id=2158-5048&m=dev) and [doc](https://docs.google.com/document/d/1ySJxQbqVdeH4Tra0zwBm2Tn0s56kFGnEF7d8xDRTxwU/edit)

## Issue / Card

Fixes https://warthogs.atlassian.net/browse/WD-11309

2024-06-14 12:05 UTC, webteam-app commented
### [<img src='https://assets.ubuntu.com/v1/6baef514-ubuntu-circle-of-friends-large.svg' height=32 width=32> Demo</img>](https://ubuntu-com-13955.demos.haus)
### [<img src='https://assets.ubuntu.com/v1/e512b0e2-jenkins.svg' height=32 width=32> Jenkins </img>](https://jenkins.canonical.com/webteam/job/start-demo/396)
### [<img src='https://assets.ubuntu.com/v1/7144ec6d-logo-jaas-icon.svg' height=32 width=32> demos.haus </img>](https://demos.haus)

2024-06-14 16:58 UTC, lyubomir-popov commented
ca nwe make this image touch the bottom? 
![image](https://github.com/canonical/ubuntu.com/assets/2741678/7c726a28-005e-4751-873f-6ffcb89286d3)

2024-06-14 17:00 UTC, lyubomir-popov commented
![image](https://github.com/canonical/ubuntu.com/assets/2741678/b5f55b6f-3e2e-4910-86f2-73bb91e091db)
some misalignments (missing nudge?)

2024-06-17 13:07 UTC, mtruj013 commented on templates/hpe/index.html
> -        attrs={"class": "u-aspect-ratio--2-3"}
Change here

2024-06-17 13:08 UTC, mtruj013 commented on templates/hpe/index.html
> -          attrs={"class": "u-aspect-ratio--2-3"}
Change here

2024-06-17 13:08 UTC, mtruj013 commented on templates/hpe/index.html
> -        attrs={"class": "u-aspect-ratio--2-3"}
Change here

2024-06-17 13:08 UTC, mtruj013 commented on templates/hpe/index.html
> -          attrs={"class": "u-aspect-ratio--2-3"}
Change here

2024-06-17 13:08 UTC, mtruj013 commented on templates/hpe/index.html
> -          attrs={"class": "u-aspect-ratio--2-3"}
Change here

2024-06-17 13:10 UTC, mtruj013 commented on templates/hpe/index.html
>  {% extends "hpe/_base_hpe.html" %}
Large diff only due to linting, please see comments in below where I've flagged the minor changes

2024-06-17 21:29 UTC, lyubomir-popov commented
- no need for the p-section class on this paragraph
![image](https://github.com/canonical/ubuntu.com/assets/2741678/5438d307-3ea1-4288-b834-c104e6945dfc)
- we need to replace this image with one that has 2.4v aspect ratio
![image](https://github.com/canonical/ubuntu.com/assets/2741678/1b72dd59-84cd-45ea-bc3c-1b8e899f1e86)
- no need for thess p-section--shallow classes, adds too much space there:
![image](https://github.com/canonical/ubuntu.com/assets/2741678/af106141-12cb-489d-9b41-cc969b50d240)
(review not finished)

2024-06-18 17:18 UTC, bartaz commented on static/sass/_pattern-image-ratios.scss
> +// XXX: MPT: Can be removed once this is live on Vanilla
Not needed anymore with 4.13

2024-06-18 20:41 UTC, lyubomir-popov commented
@mtruj013 can you pls cherrypick the last commit from [this branch](https://github.com/canonical/ubuntu.com/tree/landing-refresh-lyubo) - that's the visual QA.

2024-06-21 04:27 UTC, britneywwc requested changes
Thanks @mtruj013! I left a couple comments to address some missing/incorrect links and list stylings, besides that everything looks good!

2024-06-21 04:27 UTC, britneywwc commented on templates/base_index.html
>        </ul>
![Screenshot 2024-06-21 at 12 00 49 PM](https://github.com/canonical/ubuntu.com/assets/62298176/a7a827f0-f3cc-4520-8f5b-f234893d8ee2)
There is some top padding on the second row of list items. Can you please add "u-no-padding--top" to the list items on lines 1097 and 1100?

2024-06-21 04:27 UTC, britneywwc commented on templates/base_index.html
> +            <a href="/contact-us" class="js-invoke-modal p-button is-dark">Let's talk open source&nbsp;&rsaquo;</a>
The button text is showing link colours here, it should be showing normal text colours like other buttons
![Screenshot 2024-06-21 at 12 09 33 PM](https://github.com/canonical/ubuntu.com/assets/62298176/47fbafbf-d066-4dff-a967-acb022ed20b0)

2024-06-21 04:27 UTC, britneywwc commented on templates/base_index.html
>          <div class="col-3 col-start-large-7 col-medium-2 col-medium-start-3">
There is some top padding on the last row of list items. Can you please add "u-no-padding--top" to the list items on lines 417 and 420?

2024-06-21 13:08 UTC, mtruj013 commented on templates/base_index.html
> +          <h2 class="p-heading--1 u-no-margin--bottom u-no-max-width">Multi-cloud Kubernetes and containers</h2>
Nope, design is the source of truth for layout 🙂

2024-06-24 02:26 UTC, britneywwc approved these changes
LGTM!

2024-06-24 08:30 UTC, merged