WD-10435 - intel iot page rebrand
canonical/ubuntu.com pull request #13970
Opened 2024-06-20 08:36 UTC by lizzochek

## Done

Rebrand intel-not page.

## QA

- [demo link](https://ubuntu-com-13958.demos.haus/)
- [copy doc](https://docs.google.com/document/d/1hxKzPs6e6JQaa9tBqfZ55GAXrVnEryEWBja8HlXy-lc/edit)
- [figma](https://www.figma.com/design/cVGimTPHky4h3BPXfrT6GB/24.04-U.com---download-(rebranding)?node-id=1702-5346&m=dev)
- View the site on demo
- Run through the following [QA steps](https://discourse.canonical.com/t/qa-steps/152)
- Check that the page is correctly updated according to copy doc and figma

## Issue / Card
[WD-10435](https://warthogs.atlassian.net/browse/WD-10435)

2024-06-20 08:36 UTC, webteam-app commented
### [<img src='https://assets.ubuntu.com/v1/6baef514-ubuntu-circle-of-friends-large.svg' height=32 width=32> Demo</img>](https://ubuntu-com-13970.demos.haus)
### [<img src='https://assets.ubuntu.com/v1/e512b0e2-jenkins.svg' height=32 width=32> Jenkins </img>](https://jenkins.canonical.com/webteam/job/start-demo/1208)
### [<img src='https://assets.ubuntu.com/v1/7144ec6d-logo-jaas-icon.svg' height=32 width=32> demos.haus </img>](https://demos.haus)

2024-06-21 10:21 UTC, juanruitina commented
There were a handful of repetitive small tweaks needed, so I went ahead and applied them myself. Hope that's OK.

There's some weird behaviour of the equal heights component on medium screens (see below), what can we do about it? Just stacking the three boxes would do the trick for me. / @lyubomir-popov 

![Screenshot 2024-06-21 at 12 20 39](https://github.com/canonical/ubuntu.com/assets/1409729/c64435e7-1e1d-4046-8cb0-394e46a031f4)

2024-06-26 09:31 UTC, lyubomir-popov commented
this h2 needs to be wrapped in a p-section--shallow:
![image](https://github.com/canonical/ubuntu.com/assets/2741678/6f6b5bd4-2f1f-4451-b42d-6447baa75d9e)

2024-06-26 10:06 UTC, lyubomir-popov commented
> There's some weird behaviour of the equal heights component on medium screens (see below), what can we do about it? Just stacking the three boxes would do the trick for me. / @lyubomir-popov

I think they are just stacking, that's why it looks a little under designed. Or did you have something else in mind?

2024-06-26 10:10 UTC, lyubomir-popov commented
@juanruitina oh the markup is incorrect, this is what it should be like: 
![image](https://github.com/canonical/ubuntu.com/assets/2741678/67d0e0f0-a5e3-43ff-8a6f-8ffd72fbd847)

2024-06-26 10:36 UTC, lizzochek commented
@juanruitina @lyubomir-popov updated according to your comments

2024-06-27 09:20 UTC, lyubomir-popov commented
these two should be in a single code snippet, at the moment theres two `pre`s, causing too much space between lines
![image](https://github.com/canonical/ubuntu.com/assets/2741678/f23b2a89-0918-41b3-b982-a6a04933e5c9)

this looks wrong - 2 "ands", 3 times the amount of text that should be in a title - @Sophie-32 is it possible to shorten or breakoff part of the heading and put it in a paragraph following the heading?:
![image](https://github.com/canonical/ubuntu.com/assets/2741678/9a03e5c0-6a2a-4bb0-b06d-60788d954766)

the last section before the footer on every page should have p-section--deep on it, to doulbe the amount of white space at the bottom:
![image](https://github.com/canonical/ubuntu.com/assets/2741678/2114a9ee-d592-4155-b2c5-dbe761467ed7)

2024-06-28 05:54 UTC, akbarkz requested changes

2024-06-28 05:54 UTC, akbarkz commented on templates/download/iot/intel-iot.html
> +                      notes for
please remove the white space here

2024-06-28 05:54 UTC, akbarkz commented on templates/download/iot/intel-iot.html
> +                      notes for
please remove a white space here

2024-06-28 05:54 UTC, akbarkz commented on templates/download/iot/intel-iot.html
> +            12th Gen Intel&reg; Core&trade; processors (code name Alder Lake S and Alder Lake N)
```suggestion
            12th Gen Intel&reg; Core&trade; processors (codename Alder Lake S and Alder Lake N)
```

2024-06-28 05:54 UTC, akbarkz commented on templates/download/iot/intel-iot.html
> +        <a aria-href="https://www.intel.com/content/www/us/en/products/docs/processors/core/11th-gen-core-enhanced-for-iot-brief.html">Read
```suggestion
        <a href="https://www.intel.com/content/www/us/en/products/docs/processors/core/11th-gen-core-enhanced-for-iot-brief.html">Read
```

2024-07-01 09:51 UTC, akbarkz commented on templates/download/iot/intel-iot.html
> +                      notes for
white space

2024-07-01 09:51 UTC, akbarkz commented on templates/download/iot/intel-iot.html
> +                      notes for
white space

2024-07-01 09:51 UTC, akbarkz commented on templates/download/iot/intel-iot.html
> +                      notes for
white space

2024-07-01 09:51 UTC, akbarkz commented on templates/download/iot/intel-iot.html
> +                      notes for
white space

2024-07-01 09:51 UTC, akbarkz commented on templates/download/iot/intel-iot.html
> +                      notes for
white space

2024-07-01 09:51 UTC, akbarkz commented on templates/download/iot/intel-iot.html
> +                      notes for
white space

2024-07-01 09:51 UTC, akbarkz commented on templates/download/iot/intel-iot.html
> +                      notes for
white space

2024-07-01 09:51 UTC, akbarkz commented on templates/download/iot/intel-iot.html
> +                      notes for
white space

2024-07-01 09:51 UTC, akbarkz commented on templates/download/iot/intel-iot.html
> +                      notes for
white space

2024-07-01 09:51 UTC, akbarkz commented on templates/download/iot/intel-iot.html
> +                      notes for
white space

2024-07-01 09:51 UTC, akbarkz commented on templates/download/iot/intel-iot.html
> +                      for
white space

2024-07-01 09:51 UTC, akbarkz commented on templates/download/iot/intel-iot.html
> +                      notes for
white space

2024-07-01 09:51 UTC, akbarkz commented on templates/download/iot/intel-iot.html
> +                      for
white space

2024-07-01 09:51 UTC, akbarkz commented on templates/download/iot/intel-iot.html
> +                      notes for
white space

2024-07-01 09:51 UTC, akbarkz commented on templates/download/iot/intel-iot.html
> +                      notes for
white space

2024-07-01 09:54 UTC, akbarkz approved these changes

2024-07-01 10:12 UTC, merged