WD-11736 build /pro/devices page
canonical/ubuntu.com pull request #14028
Opened 2024-07-02 20:53 UTC by minkyngkm

***Blocked*** by logos

## Done

- Build /pro/devices page and its contact form 

## QA

- Go to /pro/devices

## Issue / Card

Fixes #

2024-07-02 20:53 UTC, webteam-app commented
### [<img src='https://assets.ubuntu.com/v1/6baef514-ubuntu-circle-of-friends-large.svg' height=32 width=32> Demo</img>](https://ubuntu-com-14028.demos.haus)
### [<img src='https://assets.ubuntu.com/v1/e512b0e2-jenkins.svg' height=32 width=32> Jenkins </img>](https://jenkins.canonical.com/webteam/job/start-demo/3169)
### [<img src='https://assets.ubuntu.com/v1/7144ec6d-logo-jaas-icon.svg' height=32 width=32> demos.haus </img>](https://demos.haus)

2024-07-03 08:34 UTC, anthonydillon commented
@lyubomir-popov we are missing a few scaled logo's here if you could help please?

2024-07-03 09:04 UTC, minkyngkm commented
@lyubomir-popov I made a comment in the [copy doc](https://docs.google.com/document/d/1i_3nPkSpCQJ4jfOwN380sdfuTxaiDuDIgDfk01wVPqo/edit?disco=AAABORyEm1g) for the logos and this is [the devices page](https://ubuntu-com-14028.demos.haus/pro/devices) I built, for your reference 🙏

2024-07-03 09:05 UTC, minkyngkm commented
@leiaru-c the demo for the page is [here](https://ubuntu-com-14028.demos.haus/pro/devices) 🙏

2024-07-03 09:33 UTC, anthonydillon requested changes
Nice work @minkyngkm, Few comments and suggestions in the code.

2024-07-03 09:33 UTC, anthonydillon commented on static/sass/_pattern_lists.scss
> +  .p-list--ticked--small {
Is this a new component? Can you raise an issue on Vanilla and comment it here please?

2024-07-03 09:33 UTC, anthonydillon commented on templates/pro/devices.html
> +      <div class="p-suru u-no-padding--top"></div>
You can wrap the containing `p-strip` with `p-suru` to add the decorator to the end of the strip.

2024-07-03 09:33 UTC, anthonydillon commented on templates/pro/devices.html
> +                    title="YouTube video player"
Can you give this a better title please?

2024-07-03 09:33 UTC, anthonydillon commented on templates/pro/devices.html
> +          </div>
Looks like this should go below the heading?

2024-07-03 09:33 UTC, anthonydillon commented on templates/pro/devices.html
> +            <a href="">Placeholder for IoT Security whitepaper&nbsp;&rsaquo;</a>
We should probably remove this incase it gets merged.

2024-07-03 09:33 UTC, anthonydillon commented on templates/pro/devices.html
> +              <a href="/engage/cto-guide-real-time-kernel#:~:text=A%20real%2Dtime%20system%20ensures,workloads%20on%20real%2Dtime%20systems.">Introduction to real-time kernel</a>
Probably don't need the test selector on the link

2024-07-03 09:33 UTC, anthonydillon commented on templates/templates/_footer-copyright-and-legal.html
> +      <a class="p-link--soft js-revoke-cookie-manager"><small>Manage your tracker settings</small></a>
This is invalid HTML

2024-07-03 09:33 UTC, anthonydillon commented on templates/pro/devices.html
> +              loading="auto|lazy"
```suggestion
              loading="lazy"
```

2024-07-03 09:33 UTC, anthonydillon commented on templates/pro/devices.html
> +              loading="auto|lazy"
```suggestion
              loading="lazy"
```

2024-07-03 09:33 UTC, anthonydillon commented on templates/pro/devices.html
> +              url="https://assets.ubuntu.com/v1/fa78f5b4-openjdk logo.png",
```suggestion
              url="https://assets.ubuntu.com/v1/fa78f5b4-openjdk%20logo.png",
```

2024-07-03 09:33 UTC, anthonydillon commented on templates/pro/devices.html
> +              url="https://assets.ubuntu.com/v1/5dbf023e-docker logo.png",
```suggestion
              url="https://assets.ubuntu.com/v1/5dbf023e-docker%20logo.png",
```

2024-07-03 09:33 UTC, anthonydillon commented on templates/pro/devices.html
> +          url="https://assets.ubuntu.com/v1/80342764-aaeon-logo @372px.png",
```suggestion
          url="https://assets.ubuntu.com/v1/80342764-aaeon-logo%20@372px.png",
```

2024-07-03 09:33 UTC, anthonydillon commented on templates/pro/devices.html
> +          url="https://assets.ubuntu.com/v1/acab2168-advantech-logo @372px.png",
```suggestion
          url="https://assets.ubuntu.com/v1/acab2168-advantech-logo%20@372px.png",
```

2024-07-03 09:33 UTC, anthonydillon commented on templates/pro/devices.html
> +          url="https://assets.ubuntu.com/v1/2dea272c-dfi-logo @372px.png",
```suggestion
          url="https://assets.ubuntu.com/v1/2dea272c-dfi-logo%20@372px.png",
```

2024-07-03 09:33 UTC, anthonydillon commented on templates/pro/devices.html
> +          <button href="/pro/devices#get-in-touch"
This needs to be a link to have a `href`

2024-07-03 10:30 UTC, leiaru-c commented
Nice work! I have a couple of suggestions:

1/ Heading:
It seems a bit off in terms of typography balance. Would it be possible to use the same layout that the /pro homepage on the header so it looks like this:
![image](https://github.com/canonical/ubuntu.com/assets/77273152/d5182773-d37d-41db-8134-79a439a07538)

2/ "For secure and compliant IoT device deployment" section:
I think the current setup feels a bit cluttered. I would suggest to try a layout like this one: 
![image](https://github.com/canonical/ubuntu.com/assets/77273152/ab76812d-5972-4e9e-8ac4-216d8613abaf)

3/ Logo section:
As mentioned in standup, some of these logos are too big and would need to be scaled down. Try to aim for something similar to this size (as seen on/pro): 
![image](https://github.com/canonical/ubuntu.com/assets/77273152/c394d970-91f7-4649-88f2-a1321a72ae6f)

4/ "Develop at speed with the Ubuntu ecosystem" section:
 These icons are getting phased out, so maybe try this layout: 
![image](https://github.com/canonical/ubuntu.com/assets/77273152/261f46ec-dcc6-4ad5-9a04-51241f2f4dab)

5/ "Meet your compliance requirements faster" section:
Same thing as before, I think removing the shields icon would be better.

6/ "Device management included" section:
The layout is not consistent with other similar sections, I would suggest trying something like:
![image](https://github.com/canonical/ubuntu.com/assets/77273152/bea533bd-ac47-4b3b-860b-bfe22a8cd6e7)
This would make it closer to what we have on /pro.

7/"Backed by leading ODMs" section:
As is, this section takes a big space in the page and is not very consistent with what we have on /pro. Try to use this layout instead: 
![image](https://github.com/canonical/ubuntu.com/assets/77273152/e0380d71-a494-475c-b3b5-c218abf36ce1)
Replace the "used by pro" in the screenshot with the "Backed by leading ODMs" section title and it should follow the same logic :)

8/"Resources" section:
This section is a bit difficult to parse. We can look to what was done on /pro for inspiration. I would suggest to try doing something like this:
![image](https://github.com/canonical/ubuntu.com/assets/77273152/aa8259cc-4878-421d-8700-09230c3c237a)

so it's similar to this: 
![image](https://github.com/canonical/ubuntu.com/assets/77273152/f52c4fad-ecd6-4ffe-9978-93831163b901)

In this case, the links for each section should be converted in this link CTA format with the line under the sections to draw the eye on the different options :)

8/Contact us:
Finally on this section, I would actually make it part of the previous section like this:
![image](https://github.com/canonical/ubuntu.com/assets/77273152/d99bdad8-1116-4318-9990-81f2284a63c0)

2024-07-04 13:51 UTC, anthonydillon approved these changes
Code looks good with a few small suggests and questions

2024-07-04 13:51 UTC, anthonydillon commented on templates/pro/devices.html
> +                  alt="",
We should put the component name in the alt here.

2024-07-04 13:51 UTC, anthonydillon commented on templates/pro/devices.html
> +              url="https://assets.ubuntu.com/v1/5dbf023e-docker logo.png",
Is there a reason you didn't add these changes?

2024-07-04 13:53 UTC, anthonydillon commented
QA is ok but logos need to be fixed

2024-07-08 08:40 UTC, merged