WD-12825 - rebrand /azure/fips
canonical/ubuntu.com pull request #14144
Opened 2024-08-05 10:11 UTC by lizzochek

## Done

Rebrand /azure/fips. No content was changed, layout only

## QA

- [demo link](https://ubuntu-com-14103.demos.haus/cloud/cloud-computing)
- [figma](https://www.figma.com/design/MinLlXouBnEDqaoAL3bTWC/24.10-Azure-bubble?node-id=1-2233&t=5AOamUxpwm8vWNig-0)
- View the site on demo
- Run through the following [QA steps](https://discourse.canonical.com/t/qa-steps/152)
- Check that the page is correct according to figma

## Issue / Card
[WD-12825](https://warthogs.atlassian.net/browse/WD-12825)

2024-08-05 10:11 UTC, webteam-app commented
### [<img src='https://assets.ubuntu.com/v1/6baef514-ubuntu-circle-of-friends-large.svg' height=32 width=32> Demo</img>](https://ubuntu-com-14144.demos.haus)
### [<img src='https://assets.ubuntu.com/v1/e512b0e2-jenkins.svg' height=32 width=32> Jenkins </img>](https://jenkins.canonical.com/webteam/job/start-demo/8931)
### [<img src='https://assets.ubuntu.com/v1/7144ec6d-logo-jaas-icon.svg' height=32 width=32> demos.haus </img>](https://demos.haus)

2024-08-05 10:47 UTC, lyubomir-popov commented
- shallow strip wrapping this heading pls 
![image](https://github.com/user-attachments/assets/f34cf3cf-b55d-48ce-8fef-a92b5a931da5)
- align button on the left on medium breakpoints
- this image needs to be 6 col wide, 16:9 aspect ratio:
![image](https://github.com/user-attachments/assets/1afd1a65-1adc-4590-9c41-31d8b3fb8062)
- extra line here:
 ![image](https://github.com/user-attachments/assets/194cbd5c-55d4-420f-b6b5-a21084707dd4)
- missing background here 
![image](https://github.com/user-attachments/assets/a76ccc7d-08cc-45e6-8f49-3924b03295d4)
6 columns wide pls, they are too small and centred. we never centre anything:
![image](https://github.com/user-attachments/assets/69e6bade-931a-49b7-a380-07c08ed9351f)
- deep p-section at the obttom, always - to keep the footer further apart

2024-08-06 12:12 UTC, lyubomir-popov commented
- image blurry, not stretching the full width of the parent container 
![image](https://github.com/user-attachments/assets/4ee72ef4-a398-4745-9087-320ac7944b52)
- can we pls hide the image and make the rest of this content fill the grid 
![image](https://github.com/user-attachments/assets/04379f08-9907-40f3-8363-3437ccf0cc88)
- these are too close. pls add some space between them:

![image](https://github.com/user-attachments/assets/9465c4d0-6b89-4dad-983e-4ad2433b6956)

- ![image](https://github.com/user-attachments/assets/bfd82504-2b2c-456a-b21d-0af62733ed39)
- can we please align this table column with the 7th column of the grid? so it lines up with content above/below:
![image](https://github.com/user-attachments/assets/0a03f13c-5e31-419c-8d0b-6735d1faf7c4)
- can we please do horizontal scroll in the table, and have it filling the grid on small and medium screens:
![image](https://github.com/user-attachments/assets/62ed3dc5-d725-4b38-997e-bfff409f2e80)
- same here 
![image](https://github.com/user-attachments/assets/46f59a25-4571-45bb-9499-22dadf06af82)

- gap neededa bove these. remove the prule class pls
![image](https://github.com/user-attachments/assets/df9f17f6-abdc-4131-9ee0-63654c22fc78)

2024-08-09 06:14 UTC, immortalcodes commented
- The spaces seem different here
![image](https://github.com/user-attachments/assets/ef75f777-4b22-4539-bf98-541827269d13)
![image](https://github.com/user-attachments/assets/e90b2bfd-079a-46b1-ac26-0785e8dfcb47)


-  Similarly here
![image](https://github.com/user-attachments/assets/73eb6d64-95c6-4815-8e51-e86d075534c6)
![image](https://github.com/user-attachments/assets/51db15f6-ca87-4f54-a63c-bc6fc876a48f)
- This seems a bit misalinged on medium screen
![image](https://github.com/user-attachments/assets/50491530-750b-49a2-9cc6-34ea1ece67f5)
- Similarly on small screen

2024-08-09 06:34 UTC, immortalcodes requested changes
Good Work! Some minor changes

2024-08-09 06:34 UTC, immortalcodes commented on templates/azure/fips.html
> +          and security features of <a href="https://ubuntu.com/azure/pro">Ubuntu Pro</a>, Ubuntu FIPS is a critical
```suggestion
          and security features of <a href="/azure/pro">Ubuntu Pro</a>, Ubuntu FIPS is a critical
```

2024-08-09 06:34 UTC, immortalcodes commented on templates/azure/fips.html
> +          <img class="p-image-container__image" src="https://assets.ubuntu.com/v1/9ec8c60f-azure-heroi.png" alt="" />
```suggestion
          <img class="p-image-container__image" src="https://assets.ubuntu.com/v1/9ec8c60f-azure-heroi.png" alt="Azure logo" />
```

2024-08-09 06:34 UTC, immortalcodes commented on templates/azure/fips.html
> +            <h3 class="p-heading--5 u-no-padding--top">FIPS compliant by default</h3>
[Vanilla](https://vanillaframework.io/docs/patterns/grid#nested-columns) suggests not to use pattern in nested cols

2024-08-09 06:34 UTC, immortalcodes commented on templates/azure/fips.html
> +    <div class="row--25-75-on-large">
Same nested cols here

2024-08-09 06:34 UTC, immortalcodes commented on templates/azure/fips.html
> +              Ubuntu Pro FIPS is based on <a href="https://ubuntu.com/azure/pro">Ubuntu Pro premium images</a>, with Azure
Please use shortened URL for all that are present on ubuntu.com

2024-08-09 09:54 UTC, immortalcodes approved these changes

2024-08-09 10:21 UTC, merged