Apply copy updates for /pricing/consulting
canonical/ubuntu.com pull request #14348
Opened 2024-09-26 10:02 UTC by britneywwc

## Done

- 

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/
    - Be sure to test on mobile, tablet and desktop screen sizes
- [List additional steps to QA the new features or prove the bug has been resolved]

## Issue / Card

Fixes #

## Screenshots

[If relevant, please include a screenshot.]

## Help

[QA steps](https://discourse.canonical.com/t/qa-steps/152) - [Commit guidelines](https://discourse.canonical.com/t/commit-guidelines/148)

2024-09-26 10:02 UTC, webteam-app commented
### [<img src='https://assets.ubuntu.com/v1/6baef514-ubuntu-circle-of-friends-large.svg' height=32 width=32> Demo</img>](https://ubuntu-com-14348.demos.haus)
### [<img src='https://assets.ubuntu.com/v1/e512b0e2-jenkins.svg' height=32 width=32> Jenkins </img>](https://jenkins.canonical.com/webteam/job/start-demo/17311)
### [<img src='https://assets.ubuntu.com/v1/7144ec6d-logo-jaas-icon.svg' height=32 width=32> demos.haus </img>](https://demos.haus)

2024-09-30 05:04 UTC, immortalcodes requested changes
Thanks for the PR. Very minor change

2024-09-30 05:59 UTC, britneywwc commented on templates/shared/pricing/_maas-deployment.html
> +        <li class="p-list__item is-ticked">Knowledge transfer on operating Kubeflow with Canonical tooling</li>
Thanks for the catch, pushed a commit to remove this

2024-09-30 06:14 UTC, immortalcodes approved these changes

2024-09-30 06:15 UTC, immortalcodes commented
Just a link that needs to be updated after and it should be good to merge.
Thanks @britneywwc for good work :smiley:

2024-09-30 07:33 UTC, merged