WD-14793 - add new /azure/confidential-computing page
canonical/ubuntu.com pull request #14365
Opened 2024-09-30 09:34 UTC by lizzochek

## Done

Add new /azure/confidential-computing page according to the copy doc and figma

## QA
- [demo link](https://ubuntu-com-13578.demos.haus/core/stories)
- [copy doc](https://docs.google.com/document/d/1sVaQQlm6LHyRf-Q3VSVTmqGRi0SV7gwBVczCTPWq3CE/edit#heading=h.3hmfjtayfrqm)
- [figma](https://www.figma.com/design/MinLlXouBnEDqaoAL3bTWC/24.10-ubuntu.com%2Fazure?node-id=543-1498&node-type=frame&t=GMkgEW8xbup8LJql-0)
- Check the site on the demo
- Run through the following [QA steps](https://discourse.canonical.com/t/qa-steps/152)
- Check that the page is correct according to copy doc and figma

## Issue / Card
[WD-14793](https://warthogs.atlassian.net/browse/WD-14793)

2024-09-30 09:34 UTC, webteam-app commented
### [<img src='https://assets.ubuntu.com/v1/6baef514-ubuntu-circle-of-friends-large.svg' height=32 width=32> Demo</img>](https://ubuntu-com-14365.demos.haus)
### [<img src='https://assets.ubuntu.com/v1/e512b0e2-jenkins.svg' height=32 width=32> Jenkins </img>](https://jenkins.canonical.com/webteam/job/start-demo/17811)
### [<img src='https://assets.ubuntu.com/v1/7144ec6d-logo-jaas-icon.svg' height=32 width=32> demos.haus </img>](https://demos.haus)

2024-09-30 10:57 UTC, mattea-turic commented
A couple of things looked a little off in the figma file, so I made some adjustments (discussed on mm).
Assets server can be found [here](https://assets.ubuntu.com/manager?tag=confidential-computing-page)

2024-09-30 12:11 UTC, Sophie-32 commented
@lizzochek - bullets are missing from the "Get Ubuntu confidential VMs on the Microsoft Azure marketplace" section on the demo

2024-09-30 12:39 UTC, mattea-turic commented
could you add shallow padding between the image and text here:
<img width="500" alt="Screenshot 2024-09-30 at 13 30 10" src="https://github.com/user-attachments/assets/480b02b0-bb6f-4b8c-9751-97fc01862f27">

the image there with the azure logo was also a off by a few pixels, so I realigned it now so it should be centred! Added [here](https://assets.ubuntu.com/v1/bee89574-azure-logo-updated.png)

add break here after "GPUs" pls so second line reads "on Microsoft Azure"
<img width="500" alt="Screenshot 2024-09-30 at 13 37 24" src="https://github.com/user-attachments/assets/f62c1f40-f27a-41a9-991e-9fad42f6e175">

break after "about"
<img width="1322" alt="Screenshot 2024-09-30 at 13 38 36" src="https://github.com/user-attachments/assets/369c5df9-bab1-4222-adaa-95844143ca28">

2024-10-03 08:50 UTC, britneywwc requested changes
Left some comments, can you also add the new page to sitemaps? Thanks

2024-10-03 08:50 UTC, britneywwc commented on templates/azure/confidential-computing.html
> +        <a href="https://azuremarketplace.microsoft.com/en-us/marketplace/apps?search=Canonical%20Ubuntu%20confidential%20VM&page=1">Try Ubuntu confidential VMs today&nbsp;&rsaquo;</a>
Please wrap the anchor tag in a `p`, this was a comment that I received from MPT from a previous PR

2024-10-03 08:50 UTC, britneywwc commented on templates/azure/confidential-computing.html
> +        <a href="/confidential-computing#get-in-touch">Don’t see what you’re looking for? Contact us to learn more&nbsp;&rsaquo;</a>
Similarly here, can you please wrap it in a `p`?

2024-10-03 08:50 UTC, britneywwc commented on templates/azure/confidential-computing.html
> +        <a href="/pro">Learn more about Ubuntu Pro&nbsp;&rsaquo;</a>
This should be wrapped in `p`

2024-10-03 08:50 UTC, britneywwc commented on templates/azure/confidential-computing.html
> +    <div class="u-fixed-width p-section--shallow">
```suggestion
    <div class="u-fixed-width">
```
Design doesn't have shallow padding for the header row

2024-10-03 08:50 UTC, britneywwc commented on templates/azure/confidential-computing.html
> +        <a href="https://aka.ms/accgpusignup">Sign up for the Azure preview of confidential AI with Ubuntu&nbsp;&rsaquo;</a>
Wrap in `p` as well

2024-10-04 05:17 UTC, britneywwc commented
Thanks for making the changes, can you please add the new page to the sitemaps? I'll leave a +1 once that's done :)

2024-10-04 08:50 UTC, britneywwc approved these changes

2024-10-04 08:50 UTC, merged