Rebrand certified configuration search result pages
canonical/ubuntu.com pull request #14381
Opened 2024-10-02 11:46 UTC by andrejvelichkovski

## Done

This PR rebrands the search pages under ubuntu.com/certified.

In fact there are three separate page types refactored:
* generic search results page
* category search pages:
    - `/certified/laptops`
    - `/certified/desktops`
    - `/certified/iot`
    - `/certified/servers`
    - `/certified/socs`
* vendor search pages: under: `/certified/vendor/HP` (and a few other vendors)

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/
    - Be sure to test on mobile, tablet and desktop screen sizes
- [List additional steps to QA the new features or prove the bug has been resolved]

## Issue / Card

Fixes #

## Screenshots

[If relevant, please include a screenshot.]

## Help

[QA steps](https://discourse.canonical.com/t/qa-steps/152) - [Commit guidelines](https://discourse.canonical.com/t/commit-guidelines/148)

2024-10-02 11:46 UTC, webteam-app commented
andrejvelichkovski is not a collaborator of the repo

2024-11-20 11:20 UTC, akbarkz commented
Demo instance can be accessed by this link: https://ubuntu-com-14381.demos.haus/

2024-12-12 15:05 UTC, juanruitina commented
Let's tweak the filters slightly, so they're more consistent with what we have in [CVEs](https://ubuntu.com/security/cves?q=):

![Screenshot 2024-12-12 at 15 58 54](https://github.com/user-attachments/assets/3f4026dc-ee15-45a8-b440-53800fb38531)

Please make filter heading text bold and aligned with checkbox labels. No border.

Also, please use the same two buttons in the same order ("Apply filters", "Clear all filters"), make them left aligned, and sticky. This is the CSS used in CVEs to achieve that:

```css
.cve-filter-buttons {
    background: #f3f3f3;
    bottom: 0;
    position: sticky;
    z-index: 2;
}
```

I've updated the [Figma file](https://www.figma.com/design/1gDRefkvA5TnZGWI9tdkZB/24.10-Certified-hardware?node-id=61-1903&node-type=frame&t=bVvYhMdATqGh74IO-0) to reflect the button changes.

Great work, this will definitely make the /certified experience more visually consistent.

2025-01-21 11:10 UTC, andrejvelichkovski commented
Thanks @juanruitina, I have now updated the filters to be consistent with the ones in the CVEs dashboard.

2025-01-23 08:56 UTC, juanruitina commented
Little bug on mobile: please make sure the sticky button section in the filters have the same margins as the filters themselves left and right.

![ubuntu-com-14381 demos haus_certified_laptops(iPhone SE)](https://github.com/user-attachments/assets/ed53b8b7-375b-447b-8f1c-b940dd1c0347)

Other than that, looks good to me; +1ing this already as to not block deployment.

2025-01-23 10:49 UTC, andrejvelichkovski commented
Ah, good catch, thanks for raising it! I have fixed it now. I also noticed it happens on the CVEs page, so once we have the fix approved here, I will try to open a tiny PR on that part to fix it.

I agree with you on the hover state, once we have a decision I can update the change with the hover state correctly set.

2025-02-12 17:39 UTC, mtruj013 requested changes
Thanks @andrejvelichkovski! Some comments in the code and also noticed that sometimes the vendors and releases drop down looks empty when certain categories are selected:
![image](https://github.com/user-attachments/assets/bcdaab33-ec85-43ce-b602-b606bafcb0ad)

It's not consistent though, so I'm not sure if it's something on my end, but thought I'd flag

2025-02-12 17:39 UTC, mtruj013 commented on templates/certified/search/_result-count-selector.html
> +               min-width: 5.3rem"
Looks like this is already defined in the sass file 
```suggestion
```

2025-02-13 12:49 UTC, andrejvelichkovski commented on templates/certified/desktops.html
> +  <form class="js-search-results p-section--deep">
Ah good idea, I wasn't aware of this and was driven by the idea that we should have as little HTML blocks as possible. I have now modified the code as suggested.

2025-02-14 08:47 UTC, mtruj013 approved these changes
Thanks @andrejvelichkovski , LGTM!

2025-02-14 08:50 UTC, merged