Create SBI BITS case study
canonical/ubuntu.com pull request #14424
Opened 2024-10-16 09:26 UTC by britneywwc

## Done

- [List of work items including drive-bys - remember to add the why and what of this work.]

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/
    - Be sure to test on mobile, tablet and desktop screen sizes
- [List additional steps to QA the new features or prove the bug has been resolved]

## Issue / Card

Fixes #

## Screenshots

[If relevant, please include a screenshot.]

## Help

[QA steps](https://discourse.canonical.com/t/qa-steps/152) - [Commit guidelines](https://discourse.canonical.com/t/commit-guidelines/148)

2024-10-16 09:26 UTC, webteam-app commented
### [<img src='https://assets.ubuntu.com/v1/6baef514-ubuntu-circle-of-friends-large.svg' height=32 width=32> Demo</img>](https://ubuntu-com-14424.demos.haus)
### [<img src='https://assets.ubuntu.com/v1/e512b0e2-jenkins.svg' height=32 width=32> Jenkins </img>](https://jenkins.canonical.com/webteam/job/start-demo/60)
### [<img src='https://assets.ubuntu.com/v1/7144ec6d-logo-jaas-icon.svg' height=32 width=32> demos.haus </img>](https://demos.haus)

2024-10-16 10:00 UTC, akbarkz requested changes
Can you also change the order in which case studies show up in the list view, so that the latest ones show first?

2024-10-16 10:24 UTC, mattea-turic commented
@britneywwc I've uploaded a [new logo](https://assets.ubuntu.com/v1/2003f53d-sbi%20bits%20logo.png) as elaine noticed that the current one is a little blurry. Also, one small ask is if you could pls have "canonical openstack" tgt on the last line to not leave one word handing

<img width="500" alt="Screenshot 2024-10-16 at 11 22 48" src="https://github.com/user-attachments/assets/7cfb7f2a-e994-41ff-856c-6c937fe8ca15">

and I realise visual wasn't called in for this so sorry to jump in :')

2024-10-16 10:57 UTC, eliman11 commented
All good from UX aside from the resolution of the logo and comments Mattea left in. I still don't seem to have writing access to the repo so can't change the label but feel free to add UX+1!

2024-10-17 04:28 UTC, akbarkz approved these changes

2024-10-17 04:28 UTC, merged