add check for contractItemID validity to prevent 500
canonical/ubuntu.com pull request #14435
Opened 2024-10-18 11:36 UTC by usamabinnadeem-10

## Done

- Add a check for contractItemID query parameter when scheduling an exam to prevent 500 error

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/
    - Be sure to test on mobile, tablet and desktop screen sizes
- Purchase and schedule an exam and it should go through

## Issue / Card

Fixes [WD-16047](https://warthogs.atlassian.net/browse/WD-16047)

## Help

[QA steps](https://discourse.canonical.com/t/qa-steps/152) - [Commit guidelines](https://discourse.canonical.com/t/commit-guidelines/148)

[WD-16047]: https://warthogs.atlassian.net/browse/WD-16047?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-10-18 11:36 UTC, webteam-app commented
### [<img src='https://assets.ubuntu.com/v1/6baef514-ubuntu-circle-of-friends-large.svg' height=32 width=32> Demo</img>](https://ubuntu-com-14435.demos.haus)
### [<img src='https://assets.ubuntu.com/v1/e512b0e2-jenkins.svg' height=32 width=32> Jenkins </img>](https://jenkins.canonical.com/webteam/job/start-demo/506)
### [<img src='https://assets.ubuntu.com/v1/7144ec6d-logo-jaas-icon.svg' height=32 width=32> demos.haus </img>](https://demos.haus)

2024-10-18 12:10 UTC, abhigyanghosh30 commented
This is not relevant to the error btw

2024-10-18 12:10 UTC, abhigyanghosh30 commented
The error is here https://sentry.is.canonical.com/canonical/ubuntu-com/issues/93025/?query=is%3Aunresolved%20cred

2024-11-23 08:12 UTC, anthonydillon commented
@abhigyanghosh30 can you reply to the last comment please?

2024-11-23 08:15 UTC, abhigyanghosh30 commented
Added comment in the PR review. It has not been addressed yet

2024-11-25 14:14 UTC, abhigyanghosh30 requested changes

2025-05-01 08:33 UTC, anthonydillon commented
@usamabinnadeem-10 is this still relevant?

2025-05-02 11:52 UTC, usamabinnadeem-10 commented
> @usamabinnadeem-10 is this still relevant?

This could not be reproduced as mentioned in this ticket https://warthogs.atlassian.net/browse/WD-16047
I am closing this.

2025-05-02 11:52 UTC, closed without merging