Rebrand /ceph/managed
canonical/ubuntu.com pull request #14470
Opened 2024-11-11 04:48 UTC by immortalcodes

## Done

- Rebranded /ceph/managed.
- Added support for Vanilla Macros.
- Bumped versions for Vanilla and SCSS.

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/
    - Be sure to test on mobile, tablet and desktop screen sizes
- The Vanilla and SCSS version has been updated in this PR, please look for abnormalities/irregularities across the site.
- [Copydoc](https://docs.google.com/document/d/1Ff3TDYBsukagu85dNZuK0FDdPRSjXEwS6Tv6JphXUvY/edit?tab=t.0)
- [Design](https://www.figma.com/design/ulUyOFdQ7CNy0whuJ4S2FM/Ceph-Bubble?node-id=21-6589&node-type=instance&m=dev)
- [Demo]()  

## Issue / Card

Fixes # [WD-16351](https://warthogs.atlassian.net/browse/WD-16351)

[QA steps](https://discourse.canonical.com/t/qa-steps/152) - [Commit guidelines](https://discourse.canonical.com/t/commit-guidelines/148)

2024-11-11 04:48 UTC, webteam-app commented
### [<img src='https://assets.ubuntu.com/v1/6baef514-ubuntu-circle-of-friends-large.svg' height=32 width=32> Demo</img>](https://ubuntu-com-14470.demos.haus)
### [<img src='https://assets.ubuntu.com/v1/e512b0e2-jenkins.svg' height=32 width=32> Jenkins </img>](https://jenkins.canonical.com/webteam/job/start-demo/3080)
### [<img src='https://assets.ubuntu.com/v1/7144ec6d-logo-jaas-icon.svg' height=32 width=32> demos.haus </img>](https://demos.haus)

2024-11-11 11:29 UTC, immortalcodes commented
> @immortalcodes I get a 500 on that page now: https://ubuntu-com-14470.demos.haus/ceph/managed

Yes, I am in process of fixing that, apparently it seems the "demo" is still running on old version of Vanilla, the page works perfect in local environment.

2024-11-11 14:27 UTC, eliman11 commented
Thanks Madhur, looks good to me! Just spotted a couple minor spelling/copy changes which I also noted down on the copy doc. 
- [ ] Change "customise" to "customize" in the 3rd bullet point under "Why choose Canonical’s Managed Ceph?"
- [ ] Change "favoured" to "favored" under "Companies using Ceph"
- [ ] Remove chevrons at the end of the links under "Learn more about Ceph" block
- [ ] Will defer to @mattea-turic but the spacing and alignment of the logos look off to me on tablet
<img width="561" alt="Screenshot 2024-11-11 at 14 20 07" src="https://github.com/user-attachments/assets/c22eb6eb-5bce-483b-b8c9-108a814d0600">

Feel free to add UX+1 once you've made those copy changes.

2024-11-11 14:49 UTC, anthonydillon requested changes
Couple of comments in the code.

2024-11-11 14:49 UTC, anthonydillon commented on templates/ceph/managed.html
> +      <a href="/ceph/contact-us" class="p-button--positive">Get in touch</a>
This should have a class to trigger the interactive form.

2024-11-11 14:49 UTC, anthonydillon commented on templates/ceph/managed.html
> +  Canonical is the leading managed ceph provider, we build, support and manage ceph clusters in any location.
```suggestion
  Canonical is the leading managed Ceph provider, we build, support and manage Ceph clusters in any location.
```

2024-11-11 14:49 UTC, anthonydillon commented on templates/ceph/managed.html
> +          <hr class="p-rule--muted u-hide--large" />
HR's are not allowed inside a `ol` element.

2024-11-11 14:49 UTC, anthonydillon commented on templates/ceph/managed.html
> +          <hr class="p-rule--muted u-hide--large" />
HR's are not allowed inside a `ol` element.

2024-11-11 14:49 UTC, anthonydillon commented on templates/ceph/managed.html
> +          <hr class="p-rule--muted u-hide--large" />
HR's are not allowed inside a `ol` element.

2024-11-11 14:49 UTC, anthonydillon commented on templates/ceph/managed.html
> +          <hr class="p-rule--muted u-hide--large" />
HR's are not allowed inside a `ol` element.

2024-11-11 14:56 UTC, immortalcodes commented
> > > @immortalcodes I get a 500 on that page now: https://ubuntu-com-14470.demos.haus/ceph/managed
> > 
> > 
> > Yes, I am in process of fixing that, apparently it seems the "demo" is still running on old version of Vanilla, the page works perfect in local environment.
> 
> How can that be true? Isn't all demos freshly built? Also why would that cause a 500?

So we figured out that it was indeed vanilla, but the fact that new template files were not being copied to demo container so it seemed as if Vanilla is still on the older version.
With a minor fix to Dockerfile the new template files are being copied to desired location.

Since it was not able to find the template file it gave 500 as error code.

2024-11-11 15:03 UTC, anthonydillon commented
Oh, of course. The new templates. Interesting, thanks.

2024-11-11 15:25 UTC, mattea-turic commented
Just a few comments:

- Numbers on the list should align to starting point of hrs
<img width="500" alt="Screenshot 2024-11-11 at 15 12 35" src="https://github.com/user-attachments/assets/5d2ca7b8-20d6-44e8-a9a9-0dc5a90199c6">

- Could you use shallow padding for the "Companies using Ceph" section? My idea was to have this along with the logo section as one
- "Notable Ceph users" should be small-caps too
<img width="500" alt="Screenshot 2024-11-11 at 15 18 38" src="https://github.com/user-attachments/assets/3d9befec-ed63-43f7-a830-67edc8e877bd">


- And yeah, as @eliman11 mentioned there's something strange going on with the wrapping here on smaller screens
<img width="514" alt="Screenshot 2024-11-11 at 15 19 46" src="https://github.com/user-attachments/assets/e8075d31-6385-41e8-89ea-a5491e087c99">

2024-11-13 11:29 UTC, anthonydillon approved these changes
LGTM with small changes in the code

2024-11-14 13:02 UTC, merged