Rebrand /ceph/consulting
canonical/ubuntu.com pull request #14473
Opened 2024-11-12 12:18 UTC by britneywwc

## Done

- Rebrand /ceph/consulting
- Update shared sections in Ceph bubble for **resources** and **users**

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/
    - Be sure to test on mobile, tablet and desktop screen sizes
- [List additional steps to QA the new features or prove the bug has been resolved]

## Issue / Card

Fixes #

## Screenshots

[If relevant, please include a screenshot.]

## Help

[QA steps](https://discourse.canonical.com/t/qa-steps/152) - [Commit guidelines](https://discourse.canonical.com/t/commit-guidelines/148)

2024-11-12 12:18 UTC, webteam-app commented
### [<img src='https://assets.ubuntu.com/v1/6baef514-ubuntu-circle-of-friends-large.svg' height=32 width=32> Demo</img>](https://ubuntu-com-14473.demos.haus)
### [<img src='https://assets.ubuntu.com/v1/e512b0e2-jenkins.svg' height=32 width=32> Jenkins </img>](https://jenkins.canonical.com/webteam/job/start-demo/3231)
### [<img src='https://assets.ubuntu.com/v1/7144ec6d-logo-jaas-icon.svg' height=32 width=32> demos.haus </img>](https://demos.haus)

2024-11-19 12:00 UTC, immortalcodes requested changes
Thanks for the PR, left some minor comments and questions. Great work overall!

2024-11-19 14:53 UTC, britneywwc commented on templates/ceph/consulting.html
> +          {{ image(url="https://assets.ubuntu.com/v1/4f840180-cephadm.png",
Nice! I'll use the new hero patterns here

2024-11-19 14:55 UTC, britneywwc commented on templates/ceph/consulting.html
> +                  What's included: <sup><a href="#os-footnote">*</a></sup>
It links to the footnote at the bottom of the card

2024-11-19 14:58 UTC, britneywwc commented on templates/ceph/consulting.html
> +        <div class="p-block">
Thanks for the catch, I've updated all `p-block` instances to `p-section--shallow`

2024-11-20 01:21 UTC, mattea-turic commented
Thanks @britneywwc ! (and sorry for late reviewww)

- Could the hero image be smaller pls (the one that's part of the hoc is 600x376, but if an aspect ratio should be provided then I'd say 3:2 should be okay! Otherwise, 16:9)
- Btw I went into safari to inspect because chrome was giving me issues and the container renders super long, I think it might be to do with the image you're using? Try [this one](https://assets.ubuntu.com/v1/f2c25341-ceph-solution-design-and-delivery.png) instead maybe
<img width="500" alt="Screenshot 2024-11-20 at 00 53 21" src="https://github.com/user-attachments/assets/3f0a6bfa-82fc-40f7-8063-417eee3c236d">

- The paragraph under the list here has the right amount of spacing but it looks different compared to the figma file to the point where it looks to be too much spacing. Could you remove that padding so I can see if it looks less disjointed? 

<img width="500" alt="Screenshot 2024-11-20 at 01 01 53" src="https://github.com/user-attachments/assets/316e75b2-aa8a-49a3-aab0-70ad332cf9a9">

- Again, compared to the mockup, the title and paragraph text look a little cramped in the pricing cards. Is this inherent to vanilla or can some spacing be introduced there? Figma design for reference: 
<img width="500" alt="Screenshot 2024-11-20 at 01 11 31" src="https://github.com/user-attachments/assets/7515f969-6a05-4f8a-8d29-fb0d55abde35">

- On smaller screens, the spacing between the header and the paragraph is too much – maybe remove the padding there? Also the text, "notable ceph users", above the logos, should be small caps

<img width="500" alt="Screenshot 2024-11-20 at 01 18 20" src="https://github.com/user-attachments/assets/f97682ca-58cd-495a-b634-8b5573caf935">

- Finally, I forgot to remove the 24px vertical spacing between the list sections here, so could you remove that too pls

<img width="500" alt="Screenshot 2024-11-20 at 01 15 44" src="https://github.com/user-attachments/assets/843bc649-6819-4071-9b09-7c80f52ac9b4">

2024-11-20 10:16 UTC, britneywwc commented
@mattea-turic I've addressed your design comments in the latest commit, please have another look! The only thing I wasn't able to change is the cramped text in the cards, I think it might be a vanilla threshold. Will leave it as is for now, let me know what you think.

2024-11-20 14:14 UTC, mattea-turic commented
thank you @britneywwc , looks great!

2024-11-21 05:49 UTC, immortalcodes approved these changes
LGTM! Good Work :fireworks:

2024-11-21 09:21 UTC, merged