WD-16645 Redesigned internet-of-things/smart-city
canonical/ubuntu.com pull request #14534
Opened 2024-12-03 13:34 UTC by muhammad-ali-pk

## Done

- Redesigned ubuntu.com/internet-of-things/smart-city

## QA
- View the site in your web browser at: https://ubuntu-com-14530.demos.haus/internet-of-things/smart-city
    - Be sure to test on mobile, tablet and desktop screen sizes
- Match the website with Design and Copydoc.
  - [Design](https://www.figma.com/design/1CdIT6TV3ASf55GsnQcwXg/Internet-of-Things?node-id=2001-16261&t=4kUhsH39i1i4UsV9-1)
  - [Copydoc](https://docs.google.com/document/d/1Zh-IkLDnaqmPr4TTeUZ3mtyY2_OGW4iElfntYWZyveY)

## Issue / Card

Fixes #[16645](https://warthogs.atlassian.net/browse/WD-16645)

2024-12-03 13:34 UTC, webteam-app commented
### [<img src='https://assets.ubuntu.com/v1/6baef514-ubuntu-circle-of-friends-large.svg' height=32 width=32> Demo</img>](https://ubuntu-com-14534.demos.haus)
### [<img src='https://assets.ubuntu.com/v1/e512b0e2-jenkins.svg' height=32 width=32> Jenkins </img>](https://jenkins.canonical.com/webteam/job/start-demo/5583)
### [<img src='https://assets.ubuntu.com/v1/7144ec6d-logo-jaas-icon.svg' height=32 width=32> demos.haus </img>](https://demos.haus)

2024-12-04 10:21 UTC, eliman11 commented
Thanks Muhammad! Sorry didn't realise you had picked this page up already! I made some changes to the copydoc while I was cleaning it up yesterday concerning US spelling and suggested a change to the "IoT OTA updates" heading. Could you add these changes please (marked on copydoc)? Also,
- [ ] Add h2 tag to "TRUSTED BY LEADING SERVICE PROVIDERS, GLOBALLY" logo heading
<img width="1382" alt="Screenshot 2024-12-04 at 10 07 03" src="https://github.com/user-attachments/assets/e2fb5c35-53c2-4450-a774-3032bc661b48">

- [ ] Is there a way to configure it so that when you click and open the 'Contact us about Ubuntu Core' modal, it will open and close on the /smart-city page? Currently it takes you to https://ubuntu.com/core.

2024-12-04 11:49 UTC, eliman11 commented
> * [ ]  Is there a way to configure it so that when you click and open the 'Contact us about Ubuntu Core' modal, it will open and close on the /smart-city page? Currently it takes you to https://ubuntu.com/core.

Following discussion on MM, please link the button to this page instead: https://ubuntu.com/core/contact-us

2024-12-05 10:59 UTC, muhammad-ali-pk commented
Thanks @eliman11 Done!

2024-12-05 11:24 UTC, eliman11 commented
Looks good, thank you!

2024-12-06 05:27 UTC, muhammad-ali-pk commented
Well Thank you @mattea-turic :) The proposed changes are done!

2024-12-09 10:59 UTC, fasih-mehmood approved these changes

2024-12-09 11:27 UTC, akbarkz requested changes

2024-12-09 11:27 UTC, akbarkz commented on templates/internet-of-things/smart-city.html
> +          to <a href="/kubeflow">Kubeflow</a>. Better ML. Faster results.
this should go up

2024-12-09 11:27 UTC, akbarkz commented on templates/internet-of-things/smart-city.html
> +              government services&nbsp;&rsaquo;</a>
please fix line breaks here

2024-12-09 11:27 UTC, akbarkz commented on templates/internet-of-things/smart-city.html
> +          <a href="#get-in-touch" class="p-button--positive js-invoke-modal">Get in touch</a>
you should specify a path to a static pages for those that don't have JS enabled. But with JS enabled this should trigger opening a modal form.

2024-12-09 11:27 UTC, akbarkz commented on templates/internet-of-things/smart-city.html
> +      <a href="#get-in-touch" class="p-button--positive js-invoke-modal">Contact Canonical</a>
you should specify a path to a static pages for those that don't have JS enabled. But with JS enabled this should trigger opening a modal form.

2024-12-09 11:27 UTC, akbarkz commented on templates/internet-of-things/smart-city.html
> +            <a href="/internet-of-things/smart-displays">Learn more&nbsp;&rsaquo;</a>
please add `aria-label` to each one of these "Learn more" links, otherwise it won't be clear to people with limited sight what these links are for

2024-12-09 12:09 UTC, merged