chore: Update security docker images page
canonical/ubuntu.com pull request #14565
Opened 2024-12-12 13:45 UTC by steverydz

## Done

- [List of work items including drive-bys - remember to add the why and what of this work.]

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/
    - Be sure to test on mobile, tablet and desktop screen sizes
- [List additional steps to QA the new features or prove the bug has been resolved]

## Issue / Card

Fixes #

## Screenshots

[If relevant, please include a screenshot.]

## Help

[QA steps](https://discourse.canonical.com/t/qa-steps/152) - [Commit guidelines](https://discourse.canonical.com/t/commit-guidelines/148)

2024-12-17 10:02 UTC, britneywwc requested changes

2024-12-17 10:02 UTC, britneywwc commented on templates/security/docker-images.html
> +    <p>Yes, with a valid Ubuntu Pro subscription. Hosts or nodes running the hardened Ubuntu-based container images must be covered with Ubuntu Advantage subscriptions. You can read more about how to
```suggestion
    <p>Yes, with a valid Ubuntu Pro subscription. Hosts or nodes running the hardened Ubuntu-based container images must be covered with Ubuntu Pro subscriptions. You can read more about how to enable FIPS mode on container images <a href="/blog/fips-ubuntu-container-security-updates">in this blog post</a>.</p>
```

2024-12-17 10:07 UTC, britneywwc commented on templates/security/docker-images.html
> +      ) | safe }}
```suggestion
      {{ image(url="https://assets.ubuntu.com/v1/8b0a474a-Microsoft_.NET_logo.svg",
                      alt="Microsft .NET logo",
                      width="230",
                      height="230",
                      hi_def=True,
                      loading="auto") | safe }}
```

2024-12-17 10:44 UTC, steverydz commented
Thanks for the review @britneywwc. I've committed your suggestions

2024-12-18 02:57 UTC, britneywwc approved these changes
Thanks, looks great!

2024-12-18 08:57 UTC, merged